#!/usr/bin/env node

import { runPackageTests } from '../../tools/package-test-runner.mjs';

const sharedProcessTestFiles = [
  'src/auth/proxy-fetch.test.ts',
  'src/auth/xai-oauth.test.ts',
  'src/cantool-capability-adapter.test.ts',
  'src/compat-harness.test.ts',
  'src/context-monitor.test.ts',
  'src/coordinator/task-intake.test.ts',
  'src/eval-backlog.test.ts',
  'src/eval-runner.test.ts',
  'src/execution-kernel-registry.test.ts',
  'src/execution-kernel-selection.test.ts',
  'src/execution-kernel.test.ts',
  'src/execution-observability.test.ts',
  'src/execution-static-graph.test.ts',
  'src/execution-transitions.test.ts',
  'src/ga-branch-hygiene.test.ts',
  'src/ga-circuit-breaker.test.ts',
  'src/ga-loop-integration.test.ts',
  'src/governance-auditors-migration.test.ts',
  'src/governance-reconciliation.test.ts',
  'src/governance-runtime-cleanup.test.ts',
  'src/governance-status-constraints.test.ts',
  'src/identity-loader.test.ts',
  'src/loop.test.ts',
  'src/loop/architect-integration.test.ts',
  'src/loop/architect-phase.test.ts',
  'src/loop/compaction-quality.test.ts',
  'src/loop/phase-tool-gate.test.ts',
  'src/loop/stop-conditions.test.ts',
  'src/loop/tool-runner.test.ts',
  'src/message-router/handlers-todo-dispatch.test.ts',
  'src/message-router/intent-resolver.test.ts',
  'src/message-router/normalizer.test.ts',
  'src/message-router/router.test.ts',
  'src/model-diagnostics.test.ts',
  'src/model-profiles.test.ts',
  'src/model-settings.test.ts',
  'src/model-tiering.test.ts',
  'src/pi-execution-kernel.test.ts',
  'src/pi-kernel-admission.test.ts',
  'src/pi-kernel-shadow-fixtures.test.ts',
  'src/pi-kernel-shadow-live.test.ts',
  'src/pi-kernel-shadow-scenario-runner.test.ts',
  'src/pi-kernel-shadow-scenarios.test.ts',
  'src/pi-kernel-shadow.test.ts',
  'src/planning-output.test.ts',
  'src/pre-action-gate.test.ts',
  'src/provider-routing-boundary.test.ts',
  'src/providers/finish-reason.test.ts',
  'src/providers/model-routing.test.ts',
  'src/providers/provider-fallback.test.ts',
  'src/providers/provider-health.test.ts',
  'src/providers/provider-policy.test.ts',
  'src/tools/core/builtin-mcp-servers.test.ts',
  'src/providers/repair-pipeline.test.ts',
  'src/providers/repair/healing.test.ts',
  'src/providers/repair/storm.test.ts',
  'src/providers/responses-adapter.test.ts',
  'src/review-runner.test.ts',
  'src/run-contract.test.ts',
  'src/run-state-vocabulary.test.ts',
  'src/runtime-adapter/grok.test.ts',
  'src/scenario-economics-runner.test.ts',
  'src/scheduler/ssh-client.test.ts',
  'src/security-gate.test.ts',
  'src/semantic-eviction.test.ts',
  'src/session-events-visibility.test.ts',
  'src/session-recovery-checkpoints.test.ts',
  'src/session-trace.test.ts',
  'src/session.test.ts',
  'src/spec-loader.test.ts',
  'src/static-analysis.test.ts',
  'src/static-graph-baselines.test.ts',
  'src/stream-checkpoints-latest.test.ts',
  'src/todo-seeds.test.ts',
  'src/tools/builtin/worker-ask-tools.test.ts',
  'src/tools/external/mcp-client.test.ts',
  'src/tools/registry.test.ts',
];

// Full isolated classification always includes every group so local
// `pnpm --filter @los/agent test` and CI group lanes share one inventory.
const isolatedGroupA = [
  'src/agent-task-graph.test.ts',
  'src/daily-agent-quality.test.ts',
  'src/dead-letter.test.ts',
  'src/eval-probes.test.ts',
  'src/execution-experiments.test.ts',
  'src/execution-outbox.test.ts',
  'src/execution-store.test.ts',
  'src/executor-nodes.test.ts',
  'src/external-tool-summary.test.ts',
  'src/feed-analysis-integration.test.ts',
  'src/governance-drift-sweeper.test.ts',
  'src/governance-jobs.test.ts',
  'src/governance-sweep-todos.test.ts',
  'src/governance-sweeper.test.ts',
  'src/governance-wake.test.ts',
  'src/kernel-event-projection.test.ts',
  'src/managed-workspaces.test.ts',
  'src/mcp-distribution.test.ts',
  'src/message-router/handlers-run-contract.test.ts',
];

const isolatedGroupB = [
  'src/operator-control-consumer.test.ts',
  'src/operator-control.test.ts',
  'src/pi-kernel-envelope.test.ts',
  'src/pi-kernel-input.test.ts',
  'src/pre-action-evidence.test.ts',
  'src/provider-compat-evidence.test.ts',
  'src/provider-promotion-decisions.test.ts',
  'src/providers.test.ts',
  'src/run-evals-pairwise.test.ts',
  'src/run-evals-sample-gate.test.ts',
  'src/run-evals.test.ts',
  'src/run-spec-plans.test.ts',
  'src/run-spec-kernel-selection.test.ts',
  'src/run-specs.test.ts',
  'src/runtime-evidence-graph.test.ts',
  'src/scenario-economics.test.ts',
  'src/scheduled-work.test.ts',
  'src/scheduler-kernel-shadow.test.ts',
  'src/scheduler-planning.test.ts',
  'src/scheduler.test.ts',
];

const isolatedGroupC = [
  'src/scheduler/executor-client.test.ts',
  'src/scheduler/task-heartbeat.test.ts',
  'src/self-check.test.ts',
  'src/service-instances.test.ts',
  'src/skill-distribution.test.ts',
  'src/stream-checkpoints.test.ts',
  'src/stream-lease.test.ts',
  'src/task-runs.test.ts',
  'src/task-runs/blocked-resume.test.ts',
  'src/todo-dispatch.test.ts',
  'src/todos.test.ts',
  'src/tool-call-recovery.test.ts',
  'src/verification-records.test.ts',
  'src/work-items.test.ts',
  'src/work-items/revision-loop.test.ts',
  'src/worker-messages.test.ts',
  'src/session-recovery.test.ts',
];

const allIsolatedDatabaseTestFiles = [
  ...isolatedGroupA,
  ...isolatedGroupB,
  ...isolatedGroupC,
];

const testGroup = process.env.LOS_TEST_GROUP;
const isolatedDatabaseTestFiles = testGroup === '1'
  ? isolatedGroupA
  : testGroup === '2'
    ? isolatedGroupB
    : testGroup === '3'
      ? isolatedGroupC
      // unset / unknown: run every isolated file (local full package test)
      : allIsolatedDatabaseTestFiles;

runPackageTests({
  packageId: 'agent',
  sharedProcessTestFiles,
  isolatedDatabaseTestFiles,
  // Classification always validates the full inventory even when CI runs one group.
  classifiedIsolatedDatabaseTestFiles: allIsolatedDatabaseTestFiles,
  testSetupFile: './src/test-setup.ts',
  globalSetupFile: './src/test-global-setup.mjs',
});
