/**
 * @los/agent — Public API.
 */

export { runAgent, type AgentConfig, type AgentModelDelta, type AgentResult, type ToolCallStateTransition, type TurnSummary, type CheckpointState } from './loop.js';
export { getDefaultSystemPrompt } from './loop/message-builder.js';
export {
  cancelScheduledTask,
  runAgentTaskGraphSerial,
  runScheduledAgentTask,
  type RunAgentTaskGraphSerialInput,
  type RunAgentTaskGraphSerialResult,
  type ScheduledAgentTaskInput,
  type ScheduledAgentTaskResult,
  type ScheduledTaskEvent,
  type ScheduledTaskEventType,
} from './scheduler.js';
export { createProvider, createDeepSeekProvider, createOpenAIProvider, type ChatOptions, type Provider, type ProviderDelta, type Message, type ToolCall, type ProviderResponse, type CreateProviderOptions, type ProviderModelInfo } from './providers/index.js';
export { normalizeModelSettings, type ModelSettings } from './model-settings.js';
export {
  MODEL_PROFILES,
  calculateCost,
  estimateCost,
  resolveModelCapabilityProfile,
  resolveModelProfile,
  summarizeModelProfile,
  type ApiShape,
  type CachePolicy,
  type CostEstimate,
  type ModelCapabilityProfile,
  type ModelExecutionSummary,
  type ModelPricing,
  type ModelProfile,
  type ProviderProtocol,
  type ResolveModelProfileOptions,
  type SessionAffinity,
  type ToolCallRepairMode,
  type TransportHint,
  type VisionCapabilityMode,
} from './model-profiles.js';
export {
  ADVISORY_COMPATIBILITY_TARGETS,
  DEFAULT_COMPATIBILITY_PROBES,
  DEFAULT_COMPATIBILITY_TARGETS,
  createCompatibilityRunSpecs,
  parseCompatibilityTarget,
  parseCompatibilityTargets,
  resolveRequiredCompatibilityTargets,
  resolveRequiredCompatibilityTargetsWithDefaultDb,
  selectCompatibilityProbes,
  summarizeCompatibilityEvents,
  target,
  type CompatibilityHarnessOptions,
  type CompatibilityProbe,
  type CompatibilityRunSpec,
  type CompatibilityRunSummary,
  type CompatibilitySseEvent,
  type CompatibilityToolMode,
  type ProviderModelTarget,
} from './compat-harness.js';
export {
  createToolRegistry,
  registerBuiltinTools,
  READ_ONLY_BUILTIN_TOOLS,
  setWorkspaceRoot,
  type ToolRegistry,
  type ToolRegistryOptions,
  type BuiltinToolOptions,
  type ToolCapability,
  type ToolCostLevel,
  type ToolExecutionPolicy,
  type ToolExecutionDecision,
  type ToolHandler,
  type ToolInput,
  type ToolRetryPolicy,
  type ToolRiskLevel,
  type ToolResult,
} from './tools/registry.js';
export { MCPToolBridge, MCPClient, type MCPServerConfig, type MCPToolDef, type MCPServerRegistryRecord, registryRecordToConfig } from './tools/mcp-client.js';
export {
  ensureMCPServerStore,
  upsertMCPServer,
  loadMCPServer,
  listMCPServers,
  deleteMCPServer,
  updateMCPServerStatus,
  type MCPServerRecord,
  type MCPTransport,
  type MCPServerStatus,
  type MCPRegisteredTool,
  type UpsertMCPServerInput,
  type UpdateMCPServerStatusInput,
  type ListMCPServersOptions,
} from './mcp-servers.js';
export { ensureSessionStore, saveSession, loadSession, listSessions, deleteSession, type SessionRecord } from './session.js';
export {
  recordOperatorFollowup,
  recordOperatorSteering,
  recordSessionBranchCreated,
  type RecordOperatorFollowupInput,
  type RecordOperatorSteeringInput,
  type RecordSessionBranchCreatedInput,
} from './operator-control.js';
export {
  ensureToolCallStateStore,
  createToolCallState,
  // updateToolCallState — internal; use transitionExecutionState for state changes
  loadToolCallState,
  listToolCallStates,
  listToolCallStatesForTaskRun,
  listToolCallStatesForRunSpec,
  type ToolCallStateRecord,
  type ToolCallStateType,
  type CreateToolCallStateInput,
  type UpdateToolCallStateInput,
} from './tool-call-states.js';
export {
  applyToolCallRecoveryTransitionForRunSpec,
  evaluateToolCallRecovery,
  readToolCallRecoveryForRunSpec,
  readToolCallRecoveryForTaskRun,
  type ToolCallRecoveryDecision,
  type ToolCallRecoveryIntent,
  type ToolCallRecoveryOptions,
  type ToolCallRecoveryRecommendation,
  type ToolCallRecoveryTransitionAction,
  type ToolCallRecoveryTransitionResult,
} from './tool-call-recovery.js';
export {
  ExecutionTransitionError,
  assertExecutionTransition,
  canTransitionExecutionState,
  evaluateExecutionTransition,
  executionTransitionEventType,
  isTerminalExecutionState,
  type ExecutionEntityType,
  type ExecutionState,
  type ExecutionStateByEntity,
  type ExecutionTransitionInput,
  type ExecutionTransitionResult,
} from './execution-transitions.js';
export {
  ensureExecutionStore,
  transitionExecutionState,
  type ExecutionEventEnvelope,
  type TransitionExecutionStateInput,
  type TransitionExecutionStateResult,
} from './execution-store.js';
export {
  ensureRunSpecStore,
  claimRunSpec,
  createRunSpec,
  approveRunSpecPhase,
  loadRunSpec,
  reviseRunSpecPlan,
  listRunSpecs,
  listRunSpecsForSession,
  // updateRunSpecStatus — internal; use transitionExecutionState for state changes
  type RunSpecRecord,
  type RunSpecStatus,
  type CreateRunSpecInput,
} from './run-specs.js';
export {
  canMarkSucceeded,
  canStartExecution,
  mergeRunContractMetadata,
  normalizeRunContractMetadata,
  readRunContractMetadata,
  validatePhaseTransition,
  type PlanStep,
  type RunContractMetadata,
  type RunContractMetadataInput,
  type RunContractMode,
  type RunPhase,
  type VerificationRequirement,
} from './run-contract.js';
export { loadSpecsForFiles, loadAllSpecs, resolveSpecLayer, type LoadedSpec, type SpecLayer } from './spec-loader.js';
export { runLifecycleHooks, type RunHookInput, type HookEvent } from './lifecycle-hooks.js';
export {
  createVerificationRecord,
  ensureVerificationRecordStore,
  listVerificationRecordsForRunSpec,
  listVerificationRecordsForSession,
  loadVerificationRecord,
  seedVerificationRequirementsForRunSpec,
  updateVerificationRecord,
  type CreateVerificationRecordInput,
  type UpdateVerificationRecordInput,
  type VerificationRecord,
  type VerificationRecordStatus,
} from './verification-records.js';
export {
  resolveVerificationCompletionDecision,
  runVerificationRecord,
  runVerificationRecordsForRunSpec,
  type RunVerificationRecordOptions,
  type RunVerificationRecordResult,
  type RunVerificationRecordsForRunSpecOptions,
  type RunVerificationRecordsForRunSpecResult,
  type VerificationCommandResult,
  type VerificationCompletionDecision,
} from './verification-runner.js';
export {
  ensureProviderCompatEvidenceStore,
  loadProviderCompatEvidence,
  listProviderCompatEvidence,
  listLatestProviderCompatEvidence,
  recordProviderCompatEvidence,
  recordProviderCompatEvidenceFromSummary,
  recordProviderCompatEvidenceFromSummaryWithDefaultDb,
  type ProviderCompatDecision,
  type ProviderCompatEvidenceRecord,
  type ListProviderCompatEvidenceOptions,
  type RecordProviderCompatEvidenceInput,
} from './provider-compat-evidence.js';
export {
  enforceProviderPromotionDecision,
  ensureProviderPromotionDecisionStore,
  listProviderPromotionDecisions,
  recordProviderPromotionDecision,
  type EnforceProviderPromotionDecisionInput,
  type ListProviderPromotionDecisionsOptions,
  type ProviderPromotionDecisionRecord,
  type ProviderPromotionPolicyAction,
  type ProviderPromotionPolicyStatus,
  type RecordProviderPromotionDecisionInput,
} from './provider-promotion-decisions.js';
export {
  ensureExternalToolSummaryStore,
  importExternalToolSummary,
  listExternalToolSummaries,
  normalizeExternalToolSummary,
  redactExternalSummaryText,
  type ExternalAgentTool,
  type ExternalSummaryEvidenceInput,
  type ExternalSummarySourceKind,
  type ExternalToolSummaryRecord,
  type ExternalToolSummary,
  type ExternalToolSummaryInput,
  type ListExternalToolSummariesOptions,
} from './external-tool-summary.js';
export {
  ensureRunEvalStore,
  compareRunEvals,
  listRunEvals,
  recordFailoverEval,
  recordRunEval,
  summarizeRunEvals,
  type CompareRunEvalsOptions,
  type ListRunEvalsOptions,
  type RecordRunEvalInput,
  type RunEvalComparison,
  type RunEvalFailoverScope,
  type RunEvalRecord,
  type RunEvalSummary,
  type RunEvalSummaryGroup,
  type RunEvalVerificationStatus,
  type SummarizeRunEvalsOptions,
} from './run-evals.js';
export {
  getEvalBacklogCases,
  recordEvalBacklogSnapshot,
  type EvalBacklogCase,
} from './eval-backlog-runner.js';
export {
  claimReadyAgentTasks,
  createAgentTask,
  createAgentTaskAttempt,
  ensureAgentTaskGraphStore,
  heartbeatAgentTask,
  linkAgentTaskDependency,
  listAgentTaskAttempts,
  listAgentTasksForGraph,
  listAgentTasksForRunSpec,
  listBlockedAgentTasks,
  recoverExpiredAgentTasks,
  recoverExpiredAgentTasksWithAdvisoryLock,
  updateAgentTaskStatus,
  AGENT_TASK_STARTUP_RECOVERY_LOCK_KEY,
  type AgentTaskAttemptRecord,
  type AgentTaskAttemptStatus,
  type AgentTaskEdgeRecord,
  type AgentTaskRecord,
  type AgentTaskRole,
  type AgentTaskStatus,
  type ClaimReadyAgentTasksInput,
  type CreateAgentTaskAttemptInput,
  type CreateAgentTaskInput,
  type LinkAgentTaskDependencyInput,
} from './agent-task-graph.js';
export {
  getAgentTaskGraphCompletion,
  readAgentTaskGraph,
  summarizeAgentTaskGraph,
  type AgentTaskGraphBlockReason,
  type AgentTaskGraphCompletion,
  type AgentTaskGraphCompletionOptions,
  type AgentTaskGraphCompletionStatus,
  type AgentTaskGraphReadModel,
} from './agent-task-graph-read-model.js';
export {
  ensureSchedulerDecisionLedgerStore,
  listSchedulerDecisions,
  recordSchedulerDecision,
  type ListSchedulerDecisionsOptions,
  type RecordSchedulerDecisionInput,
  type SchedulerDecisionKind,
  type SchedulerDecisionRecord,
} from './scheduler-decision-ledger.js';
export {
  buildExecutionStaticGraph,
  type BuildExecutionStaticGraphOptions,
  type ExecutionStaticEdge,
  type ExecutionStaticEdgeKind,
  type ExecutionStaticGraph,
  type ExecutionStaticNode,
  type ExecutionStaticNodeKind,
} from './execution-static-graph.js';
export {
  readRuntimeEvidenceGraph,
  type ReadRuntimeEvidenceGraphOptions,
  type RuntimeEvidenceEdge,
  type RuntimeEvidenceEdgeKind,
  type RuntimeEvidenceGraph,
  type RuntimeEvidenceNode,
  type RuntimeEvidenceNodeKind,
  type RuntimeEvidenceRecord,
} from './runtime-evidence-graph.js';
export {
  buildRunStateProjection,
  readRunStateProjection,
  type BuildRunStateProjectionInput,
  type RunStateAction,
  type RunStateBlocker,
  type RunStateBlockerKind,
  type RunStateProjection,
} from './run-state-vocabulary.js';
export {
  reconcilePlanningTodos,
  reconcilePlanningTodosFromOpenDb,
  reconcilePlanningTodosWithDefaultDb,
  type GovernanceTodoSnapshot,
  type TodoReconciliationItem,
  type TodoReconciliationOptions,
  type TodoReconciliationReport,
  type TodoStatusDrift,
} from './governance-reconciliation.js';
export {
  detectRuntimeCleanup,
  detectRuntimeCleanupFromOpenDb,
  detectRuntimeCleanupWithDefaultDb,
  type RuntimeCleanupCandidate,
  type RuntimeCleanupOptions,
  type RuntimeCleanupReport,
  type RuntimeCleanupRunSpecSnapshot,
  type RuntimeCleanupTaskRunSnapshot,
} from './governance-runtime-cleanup.js';
export {
  readStatusConstraintReportFromOpenDb,
  readStatusConstraintReportWithDefaultDb,
  summarizeStatusConstraintReport,
  validateStatusConstraintsFromOpenDb,
  validateStatusConstraintsWithDefaultDb,
  type StatusConstraintDefinition,
  type StatusConstraintReport,
  type StatusConstraintSnapshot,
  type ValidateStatusConstraintsResult,
} from './governance-status-constraints.js';
export {
  ensureGovernanceJobStore,
  createGovernanceJob,
  getGovernanceJob,
  listGovernanceJobs,
  listDueGovernanceJobs,
  updateGovernanceJob,
  deleteGovernanceJob,
  seedGovernanceJobs,
  runGovernanceSweep,
  type GovernanceJob,
  type GovernanceJobType,
  type GovernanceCadence,
  type GovernanceJobStatus,
  type CreateGovernanceJobInput,
  type UpdateGovernanceJobInput,
  type ListGovernanceJobsOptions,
  type GovernanceSweepResult,
  type GovernanceSweepJobResult,
} from './governance-jobs.js';
export {
  ensureStaticGraphBaselineStore,
  captureStaticGraphBaseline,
  getLatestBaseline,
  getBaseline,
  deleteBaseline,
  diffBaselines,
  summarizeBaselineDiff,
  type StaticGraphBaseline,
  type BaselineDiff,
  type CaptureBaselineInput,
} from './static-graph-baselines.js';
export {
  ensureTaskRunStore,
  createTaskRun,
  findActiveTaskRunByDedupeKey,
  // updateTaskRun — internal; use transitionExecutionState for state changes
  updateTaskRunFields,
  heartbeatTaskRun,
  recoverExpiredTaskRuns,
  recoverExpiredTaskRunsWithAdvisoryLock,
  loadTaskRun,
  listTaskRuns,
  listTaskRunsByStatus,
  listTaskRunsForSession,
  listTaskRunsForRunSpec,
  TASK_RUN_STARTUP_RECOVERY_LOCK_KEY,
  type CreateTaskRunInput,
  type TaskRunRecoveryResult,
  type TaskRunRecord,
  type TaskRunStatus,
  type UpdateTaskRunFieldsInput,
} from './task-runs.js';
export {
  ensureExecutorNodeStore,
  loadExecutorNode,
  listExecutorNodes,
  recordExecutorNodeProbe,
  upsertExecutorNode,
  upsertExecutorNodeHeartbeat,
  type ExecutorNodeHeartbeatInput,
  type ExecutorNodeConnectMode,
  type ExecutorNodeKind,
  type ExecutorNodeProbeInput,
  type ExecutorNodeRecord,
  type ExecutorNodeStatus,
  type ExecutorNodeUpsertInput,
} from './executor-nodes.js';
export {
  clearCancellation,
  ensureCancellationStore,
  pollCancellation,
  requestCancellation,
  type CancellationRequest,
} from './cancellation.js';
export {
  ensureServiceInstanceStore,
  evaluateServiceInstance,
  listServiceInstances,
  loadServiceInstance,
  upsertServiceInstance,
  upsertServiceInstanceHeartbeat,
  type ServiceInstanceHeartbeatInput,
  type ServiceInstanceKind,
  type ServiceInstanceReadiness,
  type ServiceInstanceRecord,
  type ServiceInstanceRole,
  type ServiceInstanceRolloutState,
  type ServiceInstanceStatus,
  type ServiceInstanceUpsertInput,
} from './service-instances.js';
export {
  ensureSessionEventStore,
  appendSessionEvent,
  appendSessionEvents,
  listSessionEvents,
  listRecentSessionEvents,
  listSessionEventsSince,
  getSessionObservability,
  projectSessionObservability,
  type SessionEventRecord,
  type SessionEventUsage,
  type SessionEventWrite,
  type SessionObservability,
} from './session-events.js';
export {
  ensureStreamCheckpointStore,
  createStreamCheckpoint,
  listStreamCheckpointsSince,
  listStreamCheckpointsForRunSpec,
  type StreamCheckpointRecord,
  type CreateStreamCheckpointInput,
} from './stream-checkpoints.js';
export {
  ensureTodoStore,
  archiveTodo,
  createTodo,
  updateTodo,
  loadTodo,
  listTodos,
  reopenTodo,
  seedLosPlanningTodos,
  unarchiveTodo,
  type CreateTodoInput,
  type ListTodosOptions,
  type TodoKind,
  type TodoPriority,
  type TodoRecord,
  type TodoStatus,
  type UpdateTodoInput,
  type SeedLosPlanningTodosOptions,
} from './todos.js';
export {
  deleteArtifact,
  ensureArtifactStore,
  listArtifacts,
  loadArtifact,
  putArtifact,
  readArtifactContent,
  type ArtifactOperation,
  type ArtifactPathPolicy,
  type ArtifactRecord,
  type ListArtifactsOptions,
  type PutArtifactInput,
} from './artifacts.js';
export {
  ensureNodeCommandStore,
  executeNodeCommand,
  listNodeCommands,
  loadNodeCommand,
  type ExecuteNodeCommandInput,
  type ListNodeCommandsOptions,
  type NodeCommandName,
  type NodeCommandRecord,
  type NodeCommandRuntime,
  type NodeCommandRuntimeContext,
  type NodeCommandRuntimeResult,
  type NodeCommandStatus,
} from './node-commands.js';
export {
  ensureSkillStore,
  upsertSkill,
  loadSkill,
  listSkills,
  deleteSkill,
  incrementSkillUsage,
  skillDirForScope,
  syncSkillsToDir,
  loadSkillsFromDir,
  type SkillRecord,
  type SkillRunMode,
  type SkillScope,
  type SkillLayer,
  type UpsertSkillInput,
} from './skills.js';
export {
  ensureRuleStore,
  upsertRule,
  loadRule,
  listRules,
  updateRuleStatus,
  deleteRule,
  ruleDirForScope,
  syncRulesToDir,
  loadRulesFromDir,
  type RuleRecord,
  type RuleScope,
  type RuleSeverity,
  type RuleEnforcementMode,
  type RuleStatus,
  type RuleLayer,
  type UpsertRuleInput,
} from './rules.js';
export {
  runPostExecutionSelfCheck,
  shouldRunSelfCheck,
  buildSelfCheckPrompt,
  parseSelfCheckResponse,
  summarizeAgentContext,
  type SelfCheckGap,
  type SelfCheckInput,
  type SelfCheckResult,
} from './self-check.js';
export {
  scanProject,
  scanFiles,
  loadRuleFiles,
  discoverFiles,
  languageFromFilePath,
  type StaticAnalysisFinding,
  type StaticAnalysisRule,
  type StaticAnalysisScanOptions,
  type StaticAnalysisScanResult,
  type StaticAnalysisConstraint,
  type StaticAnalysisRange,
  type StaticAnalysisPosition,
} from './static-analysis/index.js';

// Re-export ast-grep types for rule authors
export type { Rule as AstGrepRule } from '@ast-grep/napi';
