import type { CreateTodoInput } from './todo-types.js';

export const LOS_PLANNING_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-saas-foundation',
    title: '建立 SaaS 租户/项目/用户/节点字段骨架',
    description: '在 todos、task_runs、session_events、sessions、observations 中形成 tenant_id/project_id/user_id/node_id/request_id/trace_id 的统一约定。',
    kind: 'phase',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'saas-foundation',
    dedupeKey: 'los:todo:saas-foundation',
    metadata: {
      problem: '当前后端表结构主要只有 traceId/dedupeKey，缺少 SaaS 隔离字段。',
      solution: '先以 local/los 默认值建字段和索引，再接认证与权限。',
    },
  },
  {
    id: 'todo-los-request-id-ledger',
    title: '为每个 HTTP 请求生成 requestId 并贯穿日志和事件',
    description: 'Fastify 请求进入时生成或接收 requestId，写入 response header、logger binding、task metadata、session_events payload。',
    kind: 'task',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'saas-foundation',
    parentId: 'todo-los-saas-foundation',
    dependsOnIds: ['todo-los-saas-foundation'],
    dedupeKey: 'los:todo:request-id-ledger',
    metadata: {
      problem: 'logger 类型预留 requestId，但 gateway 没有自动生成和持久化。',
      solution: '新增 request context middleware 和统一事件字段。',
    },
  },
  {
    id: 'todo-los-idempotency-keys',
    title: '新增租户级 idempotency key 表防止请求重放',
    description: '按 tenant_id + route + idempotency_key + body_hash 记录请求状态、响应摘要和关联 todo/task。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'saas-foundation',
    parentId: 'todo-los-saas-foundation',
    dependsOnIds: ['todo-los-request-id-ledger'],
    dedupeKey: 'los:todo:idempotency-keys',
    metadata: {
      problem: '当前 dedupeKey 只防 active task 重复，不防完成后请求重放。',
      solution: '把 HTTP 幂等从任务去重中拆出来，持久化请求幂等记录。',
    },
  },
  {
    id: 'todo-los-agent-runtime-strategy',
    title: '确定 los 的 agent 工具框架边界',
    description: '评估现成 agent/tool framework 与自研薄编排层的取舍，冻结 los core 优先走内置 provider loop，并用 provider/model profile 承载服务商和模型差异。',
    kind: 'phase',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    dedupeKey: 'los:todo:agent-runtime-strategy',
    metadata: {
      problem: '如果直接引入通用框架，可能和 task_runs、session_events、tool policy、todo ledger 重叠。',
      solution: '保留 los 自己的核心执行合同，优先补 provider/model profile；Reasonix/Codex CLI 先作为参考或 fallback，不作为默认运行时。',
      adr: 'docs/adr/0007-provider-loop-first-model-profiles.md',
    },
  },
  {
    id: 'todo-los-single-node-mesh-ready-order',
    title: '固化单节点 mesh-ready 执行顺序',
    description: '先闭合 provider loop、model profile、event projection、harness 和 todo dispatch，再接 local node registry、lease/recovery，最后进入远程 executor。',
    kind: 'plan',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-agent-runtime-strategy'],
    dedupeKey: 'los:todo:single-node-mesh-ready-order',
    metadata: {
      problem: '如果先做完整 mesh，会在 agent execution contract 稳定前引入节点调度、远程连接和弱网恢复复杂度。',
      solution: '把单节点作为 nodeId=local 的 mesh-ready 节点推进，先闭合执行链路，再增加 mesh substrate。',
      adr: 'docs/adr/0008-single-node-mesh-ready-execution-order.md',
    },
  },
  {
    id: 'todo-los-agent-framework-benchmark',
    title: '对比现成 agent 框架与 los 现有执行合同',
    description: '对 OpenAI Agents SDK、LangGraph、AutoGen 等框架做轻量对比，记录它们和 los loop、tool registry、scheduler、session_events 的重叠和可借鉴点。',
    kind: 'task',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-single-node-mesh-ready-order'],
    dedupeKey: 'los:todo:agent-framework-benchmark',
    metadata: {
      problem: '框架选型如果没有证据，会在后续实现里反复摇摆。',
      solution: '用一页对比固定 adoption/rejection criteria，并把结果写入 ADR 0007。',
    },
  },
  {
    id: 'todo-los-provider-model-profile',
    title: '定义 provider/model profile 接口',
    description: '定义服务商和模型级 profile，包括 endpoint、model id、reasoning/effort、tool-call repair、cache-friendly prompt、usage/cost extraction、abort/timeout 和能力开关。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-single-node-mesh-ready-order', 'todo-los-agent-framework-benchmark', 'todo-los-request-id-ledger'],
    dedupeKey: 'los:todo:provider-model-profile',
    metadata: {
      problem: '如果只用 provider 名称区分模型，会把 DeepSeek、PackyCode/OpenAI-compatible、Reasonix/Codex 行为差异留在散落判断里。',
      solution: '在内置 provider loop 前定义模型 profile，把服务商差异收敛到稳定配置和 adapter 行为。',
      candidateModule: 'packages/agent/src/model-profiles',
    },
  },
  {
    id: 'todo-los-deepseek-reasonix-parity',
    title: '对齐 Reasonix 的 DeepSeek 调用行为',
    description: '分析 Reasonix 对 DeepSeek 的模型、effort、budget、缓存友好提示、transcript 和成本统计做法，优先在 los provider loop 内实现同类能力。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-model-profile'],
    dedupeKey: 'los:todo:deepseek-reasonix-parity',
    metadata: {
      problem: '目标不是引入 Reasonix CLI，而是让 los 调用 DeepSeek 时具备相近的模型优化和成本可观测能力。',
      solution: '先把可复用行为沉到 DeepSeek profile/provider adapter；只有无法复现的能力才保留 CLI fallback 评估。',
    },
  },
  {
    id: 'todo-los-codex-packycode-parity',
    title: '对齐 Codex/PackyCode 的 coding agent 能力',
    description: '分析 Codex 在 sandbox、approval、coding prompt、tool boundary、review/exec 行为和 PackyCode/OpenAI-compatible 路由上的可借鉴点，优先在 los agent loop 内实现。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-model-profile'],
    dedupeKey: 'los:todo:codex-packycode-parity',
    metadata: {
      problem: '目标不是必须通过 Codex CLI，而是让 los 自己具备基础 coding agent 能力，并能按服务商/模型逐步优化。',
      solution: '把可复现能力落到 tool policy、prompt、provider profile 和 event projection；CLI 只作为行为参考或后备。',
    },
  },
  {
    id: 'todo-los-model-event-projection',
    title: '归一化模型调用事件和 usage 到 session_events',
    description: '把 provider response、reasoning、tool-call repair、cache hit/miss、成本估算、模型 profile 和错误摘要映射为 session_events 与 task_runs metadata。',
    kind: 'task',
    status: 'in_progress',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-model-profile'],
    dedupeKey: 'los:todo:model-event-projection',
    metadata: {
      problem: '如果只记录模型文本和总 token，后续无法比较 DeepSeek、PackyCode/OpenAI-compatible 以及不同 profile 的真实表现。',
      solution: '定义统一 model event projection，让内置 loop 的模型行为具备可比较、可审计、可优化的证据面。',
      evidence: 'session.started / model.response 已包含 model profile 摘要，model.delta 已通过 SSE 和 executor NDJSON 转发。',
      remaining: 'cache hit/miss、成本估算、tool-call repair 结果和错误摘要还没有统一 projection。',
    },
  },
  {
    id: 'todo-los-provider-compat-harness',
    title: '建立 provider/model compatibility harness',
    description: '为 DeepSeek、PackyCode/OpenAI-compatible 和后续模型建立固定输入、工具目录、预期事件、usage/cost、错误路径、timeout/cancel 和 tool-call repair 验证。',
    kind: 'task',
    status: 'in_progress',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-model-profile', 'todo-los-model-event-projection'],
    dedupeKey: 'los:todo:provider-compat-harness',
    metadata: {
      problem: '没有 harness 时，模型适配会变成按感觉调参，无法证明不同服务商和模型的行为差异。',
      solution: '把模型调用、工具调用、失败路径、成本和事件投影做成可重复验证的 compatibility harness。',
      candidateModule: 'packages/agent/src/harness',
      evidence: 'packages/agent/src/compat-harness.ts、compat-harness.test.ts 和 los compat 已存在，默认 dry-run，--execute 可调用 /chat。',
      remaining: '真实 provider 执行、usage/cost 断言、timeout/cancel 和失败路径还没有进入稳定 CI 门禁。',
    },
  },
  {
    id: 'todo-los-cli-fallback-gate',
    title: '定义 Reasonix/Codex CLI fallback gate',
    description: '定义何时允许临时走 Reasonix/Codex CLI，包括能力缺口、cwd、权限、预算、transcript、退出码、task/session evidence 和停用条件。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-compat-harness'],
    dedupeKey: 'los:todo:cli-fallback-gate',
    metadata: {
      problem: '完全禁止 CLI fallback 会让应急能力不足；直接引入 CLI runtime 又会绕开 los 的状态和权限边界。',
      solution: '把 CLI fallback 做成有触发条件、有证据写入、有权限约束、有退出策略的应急门。',
    },
  },
  {
    id: 'todo-los-framework-reference-watch',
    title: '建立外部框架参考实现复查机制',
    description: '周期性复查 OpenAI Agents SDK、LangGraph、AutoGen、Reasonix、Codex 在工具调用、trace、handoff、sandbox、approval、harness 和恢复能力上的实现。',
    kind: 'task',
    status: 'backlog',
    priority: 'P2',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-agent-framework-benchmark'],
    dedupeKey: 'los:todo:framework-reference-watch',
    metadata: {
      problem: 'agent 框架和 CLI 工具变化很快，一次性调研会很快过期。',
      solution: '保留轻量 reference watch，把值得吸收的工程做法转成 model profile、harness 或 tool policy 任务。',
    },
  },
  {
    id: 'todo-los-node-registry',
    title: '实现 executor node registry 和 heartbeat 只读面',
    description: '先记录 node_id、role、status、capacity、queue_depth、last_seen、mesh_links，不急于开放节点维护动作。',
    kind: 'phase',
    status: 'in_progress',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'mesh-nodes',
    dedupeKey: 'los:todo:node-registry',
    dependsOnIds: ['todo-los-saas-foundation'],
    metadata: {
      problem: '节点可见性已经开始具备，但 registry、probe、UI 和调度候选仍需要统一验收。',
      solution: '继续把 node_kind、connect_modes、capabilities、verified 和 execution candidate 作为节点只读面推进。',
      evidence: 'executor_nodes 表、executor heartbeat、GET/PATCH /nodes、/nodes/:id/probe 和 Nodes 页面已存在。',
      remaining: '远程 los-node 注册、真实跨机器 agent_http_ndjson 验证、容量/队列深度和多节点候选排序还未闭合。',
    },
  },
  {
    id: 'todo-los-task-lease-recovery',
    title: '增加任务 lease、取消恢复和弱网续连',
    description: '为 running task 增加 lease_expires_at/heartbeat_at，SSE 断线后按 todo/task/session 恢复状态。',
    kind: 'task',
    status: 'in_progress',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'scheduler-recovery',
    dedupeKey: 'los:todo:task-lease-recovery',
    dependsOnIds: ['todo-los-node-registry', 'todo-los-request-id-ledger'],
    metadata: {
      problem: 'task lease 和 heartbeat 已经开始写入数据库，但弱网和进程重启后的恢复仍不完整。',
      solution: '用数据库 lease 和可恢复读取模型替代内存态唯一真相。',
      evidence: 'scheduler 创建 task_runs 时写入 heartbeat_at/lease_expires_at，gateway-local 和 executor 都会续租。',
      remaining: 'orphan recovery、SSE since/Last-Event-ID replay、跨进程 cancel 和重启后的任务恢复仍需实现。',
    },
  },
  {
    id: 'todo-los-test-db-isolation',
    title: '隔离测试数据库，避免测试任务污染 live todo/task 视图',
    description: 'task-runs 测试当前会写入有效配置的 PostgreSQL，应改为测试 schema、临时 database 或显式 cleanup。',
    kind: 'problem',
    status: 'ready',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'quality',
    dedupeKey: 'los:todo:test-db-isolation',
    dependsOnIds: ['todo-los-saas-foundation'],
    metadata: {
      problem: 'live /tasks 中可见 task-runs.test.ts 写入的 session-1 测试记录。',
      solution: '测试环境使用独立 DATABASE_URL 或清理 fixture.',
    },
  },
  {
    id: 'todo-los-governance-archive-policy',
    title: '定义 todo 归档与活跃工作集策略',
    description: 'done / cancelled todo 在完成后自动或手动归档，默认列表仅显示活跃项，避免完成项堆积干扰调度。',
    kind: 'plan',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'todo-governance',
    dedupeKey: 'los:todo:archive-policy',
    metadata: {
      problem: '大量已完成 todo 继续留在主列表里，会让活跃工作集失真。',
      solution: '引入 archived_at/archive_reason，并在默认查询中隐藏归档项。',
    },
  },
  {
    id: 'todo-los-governance-dependency-graph',
    title: '把 todo 拆分关系建成可追踪依赖图',
    description: '为 parentId 之外的跨任务前置条件增加 depends_on 关系表，便于拆分、阻塞和批次调度。',
    kind: 'task',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'todo-governance',
    parentId: 'todo-los-governance-archive-policy',
    dependsOnIds: ['todo-los-governance-archive-policy'],
    dedupeKey: 'los:todo:dependency-graph',
    metadata: {
      problem: 'parentId 只能表示树状拆分，不能表达跨分支依赖。',
      solution: '补 todo_dependencies 表和依赖查询视图。',
    },
  },
  {
    id: 'todo-los-governance-drift-sweeper',
    title: '定期核对 todo 与真实实现的漂移',
    description: '对 ready / in_progress / done todo 做证据核验，发现未更新、重复完成和实现漂移后回写状态或归档。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'todo-governance',
    parentId: 'todo-los-governance-archive-policy',
    dependsOnIds: ['todo-los-governance-archive-policy', 'todo-los-governance-dependency-graph'],
    dedupeKey: 'los:todo:drift-sweeper',
    metadata: {
      problem: 'todo 未及时更新时，页面看到的是计划真相，不是执行真相。',
      solution: '以任务事件、session_events、requestId/traceId 做核验和自动标注。',
    },
  },
  {
    id: 'todo-los-governance-saas-todo-bridge',
    title: '补租户/项目级 todo 派发接口',
    description: '按 tenantId/projectId/stageId 选择 ready 的 task/batch todo，生成 task_run 并回写 trace/request/task 关联。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'todo-governance',
    parentId: 'todo-los-governance-archive-policy',
    dependsOnIds: ['todo-los-governance-dependency-graph', 'todo-los-request-id-ledger'],
    dedupeKey: 'los:todo:saas-todo-bridge',
    metadata: {
      problem: '当前 todo 只能人工改状态，还不能成为真正的派发入口。',
      solution: '在 scheduler 前面加一层可审计的派发门。',
    },
  },
  {
    id: 'todo-los-transport-sse-ws-recovery',
    title: '补 SSE/WS 接入、续传和指数退避策略',
    description: '为 SSE/WS 增加 heartbeat、Last-Event-ID/since 续传、指数退避、jitter、最大退避上限和弱网恢复证据。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'transport-recovery',
    dependsOnIds: ['todo-los-request-id-ledger', 'todo-los-task-lease-recovery'],
    dedupeKey: 'los:todo:transport-sse-ws-recovery',
    metadata: {
      problem: '当前 /chat 只是单次 SSE 流式响应，缺少断线续传、WS 通道、退避和恢复读模型。',
      solution: '参考 vpsagentweb 的 SSE replay、agent reconnect max delay 和 WebSocket 路由经验，先固化传输策略和可验证事件。',
      placement: 'tracking in todos; implementation in gateway transport and scheduler recovery layers.',
    },
  },
  {
    id: 'todo-los-governance-module-boundary',
    title: '定义周期治理任务的模块边界',
    description: '明确一致性分析、性能优化、数据结构/存储/架构优化、实现漂移、工具层漂移和热点文件治理不放进 task_runs 主模型。',
    kind: 'plan',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'governance-jobs',
    parentId: 'todo-los-governance-archive-policy',
    dependsOnIds: ['todo-los-governance-dependency-graph'],
    dedupeKey: 'los:todo:governance-module-boundary',
    metadata: {
      problem: '如果把治理目录塞进 Tasks，会把“执行尝试”和“治理工作目录”混成一个真相面。',
      solution: 'Todos 记录治理计划和依赖；task_runs 只记录每次执行；后续独立 governance_jobs/sweeps 存周期性运行配置和结果摘要。',
      placement: 'todo-managed planning, task-run execution evidence, governance module for recurring automation when needed.',
    },
  },
  {
    id: 'todo-los-governance-periodic-sweeper',
    title: '实现周期性治理 sweeper 和租户级调度策略',
    description: '按 tenant/project 周期执行一致性、性能、存储、架构、实现漂移、工具漂移和热点文件检查，写回 todo/task/session 证据。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'governance-jobs',
    parentId: 'todo-los-governance-module-boundary',
    dependsOnIds: ['todo-los-governance-module-boundary', 'todo-los-request-id-ledger'],
    dedupeKey: 'los:todo:governance-periodic-sweeper',
    metadata: {
      problem: '定时任务如果只是 cron 调用，会缺少租户边界、幂等键、执行 lease 和可追溯结果。',
      solution: '定义 governance job policy、周期、lease、dedupeKey、result summary 和 evidence links，再通过 scheduler 执行。',
      cadenceExamples: ['daily consistency audit', 'weekly hotspot audit', 'release-gate drift audit'],
    },
  },
  {
    id: 'todo-los-governance-hotspot-and-tool-drift',
    title: '治理热点文件、实现漂移和工具层漂移',
    description: '识别超大/高频变更/跨层耦合文件，核对工具能力声明与真实行为，并把漂移结果写入 todo metadata 和 session_events。',
    kind: 'batch',
    status: 'backlog',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'governance-jobs',
    parentId: 'todo-los-governance-module-boundary',
    dependsOnIds: ['todo-los-governance-periodic-sweeper'],
    dedupeKey: 'los:todo:hotspot-tool-drift',
    metadata: {
      problem: '历史项目里工具声明、实际实现和热点文件会持续漂移，单次 review 很难长期覆盖。',
      solution: '周期性采集 file churn/size/import boundary/tool capability 与实际执行证据，生成治理 todo 或归档证据。',
      categories: ['implementation_drift', 'tool_drift', 'hotspot_files', 'architecture_drift'],
    },
  },
];
