import type { CreateTodoInput } from './todo-types.js';
import { LOS_AGENT_WORKFLOW_TODO_SEED } from './todo-seeds-agent-workflow.js';
import { LOS_GOVERNANCE_TODO_SEED } from './todo-seeds-governance.js';
import { LOS_RUNTIME_CORE_TODO_SEED } from './todo-seeds-runtime-core.js';

export const LOS_PLANNING_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-saas-foundation',
    title: '建立 SaaS 租户/项目/用户/节点字段骨架',
    description: '在 todos、task_runs、session_events、sessions、observations 中形成 tenant_id/project_id/user_id/node_id/request_id/trace_id 的统一约定。',
    kind: 'phase',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'saas-foundation',
    dedupeKey: 'los:todo:saas-foundation',
    metadata: {
      problem: '当前后端表结构主要只有 traceId/dedupeKey，缺少 SaaS 隔离字段。',
      solution: '先以 local/los 默认值建字段和索引，再接认证与权限。',
      evidence: '所有核心表 (todos/task_runs/session_events/sessions/memory_observations) 均已包含 tenant_id/project_id/user_id/node_id/request_id/trace_id，todos 表的 tenant_id+project_id 为 NOT NULL。各表均有 idx_*_tenant_project 索引。',
      implementedAt: '2026-06-09 (字段已存在，状态确认)',
    },
  },
  {
    id: 'todo-los-request-id-ledger',
    title: '为每个 HTTP 请求生成 requestId 并贯穿日志和事件',
    description: 'Fastify 请求进入时生成或接收 requestId，写入 response header、logger binding、task metadata、session_events payload。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'saas-foundation',
    parentId: 'todo-los-saas-foundation',
    dependsOnIds: ['todo-los-saas-foundation'],
    dedupeKey: 'los:todo:request-id-ledger',
    metadata: {
      problem: 'logger 类型预留 requestId，但 gateway 没有自动生成和持久化。',
      solution: '新增 request context middleware 和统一事件字段。',
      evidence: 'request-context.ts 生成/接收 requestId+trackId → response header → RequestContext.log (child logger with requestId bound) → chat-route → createTaskRun/saveSession/appendSessionEvent。所有 DB store 均已写入 request_id。',
      implementedAt: '2026-06-09 (logger binding 补齐)',
      implementedFiles: ['packages/gateway/src/request-context.ts'],
    },
  },
  {
    id: 'todo-los-idempotency-keys',
    title: '新增租户级 idempotency key 表防止请求重放',
    description: '按 tenant_id + route + idempotency_key + body_hash 记录请求状态、响应摘要和关联 todo/task。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'saas-foundation',
    parentId: 'todo-los-saas-foundation',
    dependsOnIds: ['todo-los-request-id-ledger'],
    dedupeKey: 'los:todo:idempotency-keys',
    metadata: {
      problem: '当前 dedupeKey 只防 active task 重复，不防完成后请求重放。',
      solution: '把 HTTP 幂等从任务去重中拆出来，持久化请求幂等记录。',
    },
  },
  {
    id: 'todo-los-agent-runtime-strategy',
    title: '确定 los 的 agent 工具框架边界',
    description: '评估现成 agent/tool framework 与自研薄编排层的取舍，冻结 los core 优先走内置 provider loop，并用 provider/model profile 承载服务商和模型差异。',
    kind: 'phase',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    dedupeKey: 'los:todo:agent-runtime-strategy',
    metadata: {
      problem: '如果直接引入通用框架，可能和 task_runs、session_events、tool policy、todo ledger 重叠。',
      solution: '保留 los 自己的核心执行合同，优先补 provider/model profile；Reasonix/Codex CLI 先作为参考或 fallback，不作为默认运行时。',
      adr: 'docs/adr/0007-provider-loop-first-model-profiles.md',
    },
  },
  {
    id: 'todo-los-single-node-mesh-ready-order',
    title: '固化单节点 mesh-ready 执行顺序',
    description: '先闭合 provider loop、model profile、event projection、harness 和 todo dispatch，再接 local node registry、lease/recovery，最后进入远程 executor。',
    kind: 'plan',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-agent-runtime-strategy'],
    dedupeKey: 'los:todo:single-node-mesh-ready-order',
    metadata: {
      problem: '如果先做完整 mesh，会在 agent execution contract 稳定前引入节点调度、远程连接和弱网恢复复杂度。',
      solution: '把单节点作为 nodeId=local 的 mesh-ready 节点推进，先闭合执行链路，再增加 mesh substrate。',
      adr: 'docs/adr/0008-single-node-mesh-ready-execution-order.md',
    },
  },
  {
    id: 'todo-los-agent-framework-benchmark',
    title: '对比现成 agent 框架与 los 现有执行合同',
    description: '对 OpenAI Agents SDK、LangGraph、AutoGen 等框架做轻量对比，记录它们和 los loop、tool registry、scheduler、session_events 的重叠和可借鉴点。',
    kind: 'task',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-single-node-mesh-ready-order'],
    dedupeKey: 'los:todo:agent-framework-benchmark',
    metadata: {
      problem: '框架选型如果没有证据，会在后续实现里反复摇摆。',
      solution: '用一页对比固定 adoption/rejection criteria，并把结果写入 ADR 0007。',
    },
  },
  {
    id: 'todo-los-provider-model-profile',
    title: '定义 provider/model profile 接口',
    description: '定义服务商和模型级 profile，包括 endpoint、model id、reasoning/effort、tool-call repair、cache-friendly prompt、usage/cost extraction、abort/timeout 和能力开关。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-single-node-mesh-ready-order', 'todo-los-agent-framework-benchmark', 'todo-los-request-id-ledger'],
    dedupeKey: 'los:todo:provider-model-profile',
    metadata: {
      problem: '如果只用 provider 名称区分模型，会把 DeepSeek、PackyCode/OpenAI-compatible、Reasonix/Codex 行为差异留在散落判断里。',
      solution: '在内置 provider loop 前定义模型 profile，把服务商差异收敛到稳定配置和 adapter 行为。',
      candidateModule: 'packages/agent/src/model-profiles',
    },
  },
  {
    id: 'todo-los-deepseek-reasonix-parity',
    title: '对齐 Reasonix 的 DeepSeek 调用行为',
    description: '分析 Reasonix 对 DeepSeek 的模型、effort、budget、缓存友好提示、transcript 和成本统计做法，优先在 los provider loop 内实现同类能力。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-model-profile'],
    dedupeKey: 'los:todo:deepseek-reasonix-parity',
    metadata: {
      problem: '目标不是引入 Reasonix CLI，而是让 los 调用 DeepSeek 时具备相近的模型优化和成本可观测能力。',
      solution: '先把可复用行为沉到 DeepSeek profile/provider adapter；只有无法复现的能力才保留 CLI fallback 评估。',
    },
  },
  {
    id: 'todo-los-codex-packycode-parity',
    title: '对齐 Codex/PackyCode 的 coding agent 能力',
    description: '分析 Codex 在 sandbox、approval、coding prompt、tool boundary、review/exec 行为和 PackyCode/OpenAI-compatible 路由上的可借鉴点，优先在 los agent loop 内实现。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-model-profile'],
    dedupeKey: 'los:todo:codex-packycode-parity',
    metadata: {
      problem: '目标不是必须通过 Codex CLI，而是让 los 自己具备基础 coding agent 能力，并能按服务商/模型逐步优化。',
      solution: '把可复现能力落到 tool policy、prompt、provider profile 和 event projection；CLI 只作为行为参考或后备。',
    },
  },
  {
    id: 'todo-los-model-event-projection',
    title: '归一化模型调用事件和 usage 到 session_events',
    description: '把 provider response、reasoning、tool-call repair、cache hit/miss、成本估算、模型 profile 和错误摘要映射为 session_events 与 task_runs metadata。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-model-profile'],
    dedupeKey: 'los:todo:model-event-projection',
    metadata: {
      problem: '如果只记录模型文本和总 token，后续无法比较 DeepSeek、PackyCode/OpenAI-compatible 以及不同 profile 的真实表现。',
      solution: '定义统一 model event projection，让内置 loop 的模型行为具备可比较、可审计、可优化的证据面。',
      evidence: 'session.started / model.response 已包含 model profile 摘要，model.delta 已通过 SSE 和 executor NDJSON 转发。',
      remaining: '已实现：1) 成本估算(ModelPricing + estimateCost/calculateCost)，注入 model.response.payload.cost 和 session.completed；2) model.cache 事件(含 cacheHitTokens/cacheMissTokens/savings)；3) tool.repair 事件(_repair 元数据+repairSteps)；4) session.completed.errorSummary(按 type/tool 分类的错误汇总)。',
      implementedAt: '2026-06-09',
      implementedFiles: [
        'model-profiles.ts (ModelPricing, estimateCost, calculateCost)',
        'providers/index.ts (RepairResult, _repair on ToolCall)',
        'providers/types.ts (_repair field)',
        'loop.ts (model.cache event, cost tracking, tool.repair event, errorSummary)',
        'index.ts (export CostEstimate, ModelPricing, calculateCost, estimateCost)',
      ],
    },
  },
  {
    id: 'todo-los-provider-compat-harness',
    title: '建立 provider/model compatibility harness',
    description: '为 DeepSeek、PackyCode/OpenAI-compatible 和后续模型建立固定输入、工具目录、预期事件、usage/cost、错误路径、timeout/cancel 和 tool-call repair 验证。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-model-profile', 'todo-los-model-event-projection'],
    dedupeKey: 'los:todo:provider-compat-harness',
    metadata: {
      problem: '没有 harness 时，模型适配会变成按感觉调参，无法证明不同服务商和模型的行为差异。',
      solution: '把模型调用、工具调用、失败路径、成本和事件投影做成可重复验证的 compatibility harness。',
      candidateModule: 'packages/agent/src/harness',
      evidence: 'packages/agent/src/compat-harness.ts、compat-harness.test.ts 和 los compat 已存在，默认 dry-run，--execute 可调用 /chat。',
      remaining: 'CI 门禁已完成：tools/compat-ci.sh 封装 gateway 启停 → compat --execute → 结果报告流程，支持 --json 输出和 COMPAT_TIMEOUT_MS 环境变量。DeepSeek deepseek-v4-flash 为默认 required gate，可通过 los provider policy promote/enforce 扩展。',
      implementedAt: '2026-06-09',
      implementedFiles: [
        'packages/agent/src/compat-harness.ts (harness core + tests)',
        'packages/cli/src/compat.ts (CLI entrypoint)',
        'tools/compat-ci.sh (CI gate script)',
      ],
    },
  },
  {
    id: 'todo-los-cli-fallback-gate',
    title: '定义 Reasonix/Codex CLI fallback gate',
    description: '定义何时允许临时走 Reasonix/Codex CLI，包括能力缺口、cwd、权限、预算、transcript、退出码、task/session evidence 和停用条件。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-provider-compat-harness'],
    dedupeKey: 'los:todo:cli-fallback-gate',
    metadata: {
      problem: '完全禁止 CLI fallback 会让应急能力不足；直接引入 CLI runtime 又会绕开 los 的状态和权限边界。',
      solution: '把 CLI fallback 做成有触发条件、有证据写入、有权限约束、有退出策略的应急门。',
      adr: 'docs/adr/0018-cli-fallback-gate.md',
      evidence: '当前 projects/los 没有 Reasonix/Codex CLI fallback adapter；ADR 0018 规定了能力缺口、显式触发、task_runs/session_events parity、权限 parity、预算、artifact/redaction 和退出策略。',
      remaining: '真正实现 CLI fallback adapter 仍是单独后续任务，必须先证明内置 provider loop 无法补齐目标能力。',
    },
  },
  {
    id: 'todo-los-framework-reference-watch',
    title: '建立外部框架参考实现复查机制',
    description: '周期性复查 OpenAI Agents SDK、LangGraph、AutoGen、Reasonix、Codex 在工具调用、trace、handoff、sandbox、approval、harness 和恢复能力上的实现。',
    kind: 'task',
    status: 'backlog',
    priority: 'P2',
    source: 'analysis-2026-05-30',
    stageId: 'agent-runtime',
    parentId: 'todo-los-agent-runtime-strategy',
    dependsOnIds: ['todo-los-agent-framework-benchmark'],
    dedupeKey: 'los:todo:framework-reference-watch',
    metadata: {
      problem: 'agent 框架和 CLI 工具变化很快，一次性调研会很快过期。',
      solution: '保留轻量 reference watch，把值得吸收的工程做法转成 model profile、harness 或 tool policy 任务。',
    },
  },
  {
    id: 'todo-los-node-registry',
    title: '实现 executor node registry 和 heartbeat 只读面',
    description: '先记录 node_id、role、status、capacity、queue_depth、last_seen、mesh_links，不急于开放节点维护动作。',
    kind: 'phase',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'mesh-nodes',
    dedupeKey: 'los:todo:node-registry',
    dependsOnIds: ['todo-los-saas-foundation'],
    metadata: {
      problem: '节点可见性已经开始具备，但 registry、probe、UI 和调度候选仍需要统一验收。',
      solution: '继续把 node_kind、connect_modes、capabilities、verified 和 execution candidate 作为节点只读面推进。',
      evidence: 'executor_nodes 表、executor heartbeat、GET/PATCH /nodes、/nodes/:id/probe 和 Nodes 页面已存在。',
      remaining: 'remote heartbeat 端点 (POST /nodes/heartbeat) 已实现；sortExecutorCandidates() 按 queue_depth→activeTask→capacity→heartbeat 排序已集成到 executor-client。',
      implementedAt: '2026-06-09 (remote heartbeat + candidate sorting)',
      implementedFiles: [
        'executor-nodes.ts (sortExecutorCandidates)',
        'scheduler/executor-client.ts (调用排序)',
        'node-routes.ts (POST /nodes/heartbeat)',
      ],
    },
  },
  {
    id: 'todo-los-task-lease-recovery',
    title: '增加任务 lease、取消恢复和弱网续连',
    description: '为 running task 增加 lease_expires_at/heartbeat_at，SSE 断线后按 todo/task/session 恢复状态。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'scheduler-recovery',
    dedupeKey: 'los:todo:task-lease-recovery',
    dependsOnIds: ['todo-los-node-registry', 'todo-los-request-id-ledger'],
    metadata: {
      problem: 'task lease 和 heartbeat 已经开始写入数据库，但弱网和进程重启后的恢复仍不完整。',
      solution: '用数据库 lease 和可恢复读取模型替代内存态唯一真相。',
      evidence: 'scheduler 创建 task_runs 时写入 heartbeat_at/lease_expires_at，gateway-local 和 executor 都会续租。',
      remaining: 'orphan recovery (recoverExpiredTaskRuns + orphan reaper) 已实现；SSE since/Last-Event-ID replay 已实现；跨进程 cancel (cancellation_requests 表 + task-heartbeat polling) 已实现。',
      implementedAt: '2026-06-09 (cross-process cancel)',
      implementedFiles: [
        'cancellation.ts (新文件：cancellation_requests 表+API)',
        'scheduler/task-heartbeat.ts (polling integration)',
        'routes/task-routes.ts (cross-process cancel in existing route)',
        'index.ts (exports)',
      ],
    },
  },
  {
    id: 'todo-los-service-cluster-roadmap',
    title: '固化服务集群与状态化 Agent 渐进升级路线',
    description: '把 service failover、run spec、状态机、DAG、分层记忆、工具状态和 eval 拆成可验证阶段，避免直接跳到完整 workflow engine。',
    kind: 'phase',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-01',
    stageId: 'service-cluster',
    dependsOnIds: ['todo-los-node-registry', 'todo-los-task-lease-recovery'],
    dedupeKey: 'los:todo:service-cluster-roadmap',
    metadata: {
      problem: 'executor 节点已经有 registry 雏形，但 gateway/service 仍是单入口进程；Agent 执行也还缺 durable run spec、状态机和验证面。',
      solution: '以 ADR 0012 为路线图，先做 service_instances 和 readiness，再逐步推进 run spec、stream replay、tool state、DAG、memory compression 和 eval。',
      adr: 'docs/adr/0012-service-cluster-and-stateful-agent-roadmap.md',
    },
  },
  {
    id: 'todo-los-node-identity-baseline',
    title: '纠正本机 MBP 与 node34 VM 的节点身份边界',
    description: '把 MBP 本地 executor 和局域网 node34/localnode34 VM 拆成不同 nodeId，避免 service/executor failover 决策使用混合节点记录。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-01',
    stageId: 'service-cluster',
    parentId: 'todo-los-service-cluster-roadmap',
    dependsOnIds: ['todo-los-service-cluster-roadmap'],
    dedupeKey: 'los:todo:node-identity-baseline',
    metadata: {
      problem: '当前 live /nodes 中 node34 自报 hostLabel=Echers-Mbp.local，同时又带有 node34 VM 的 SSH/Tailscale 连接信息。',
      solution: '约定 mbp-executor-1 / node34-ssh / node34-executor-1 等稳定 id，并在配置和 registry 中分开记录。',
      phase: 'ADR0012 Phase 0',
      evidence: 'mbp-executor-1 为当前在线 executor (EXECUTOR_NODE_ID=mbp-executor-1)，node34-ssh 为 LAN VM SSH target，node34 已退役。ops doc 记录 drain/rename/restart 序列。旧 node34 artifact 目录已清。',
      implementedAt: '2026-06-09 (状态确认+残留清理)',
    },
  },
  {
    id: 'todo-los-service-registry-readiness',
    title: '实现 service_instances、gateway heartbeat 和 readiness',
    description: '新增服务实例表、gateway 自注册心跳、/live、/ready、/services、drain/promote，先让 gateway 服务本身可见、可下线、可恢复。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-01',
    stageId: 'service-cluster',
    parentId: 'todo-los-service-cluster-roadmap',
    dependsOnIds: ['todo-los-service-cluster-roadmap'],
    dedupeKey: 'los:todo:service-registry-readiness',
    metadata: {
      problem: '当前 /health 只是进程级存活，不能表达 readiness、drain、DB/schema health 或多 gateway 可切流状态。',
      solution: '先实现 service plane 的最小状态面，不改变 /chat 执行路径。',
      phase: 'ADR0012 Phase 1',
    },
  },
  {
    id: 'todo-los-multi-gateway-entry',
    title: '验证多 gateway 入口与 ready-based 切流',
    description: '启动两个 gateway 实例共享 PostgreSQL，使用 /ready 做路由判断，验证 drain 一个 gateway 后新请求能进入另一个 gateway。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'analysis-2026-06-01',
    stageId: 'service-cluster',
    parentId: 'todo-los-service-cluster-roadmap',
    dependsOnIds: ['todo-los-service-registry-readiness'],
    dedupeKey: 'los:todo:multi-gateway-entry',
    metadata: {
      problem: '服务注册只证明可见性，不证明多 gateway 可承接新请求。',
      solution: '增加并发启动、startup recovery 锁和 failover smoke。',
      phase: 'ADR0012 Phase 2',
    },
  },
  {
    id: 'todo-los-run-spec-stream-replay',
    title: '新增 durable run_specs 和跨 gateway stream replay',
    description: '把 /chat 的执行意图保存为 run_specs，并提供 /runs/:id/events?since= 读取，支持客户端通过另一个 gateway 恢复展示。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'analysis-2026-06-01',
    stageId: 'run-orchestration',
    parentId: 'todo-los-service-cluster-roadmap',
    dependsOnIds: ['todo-los-multi-gateway-entry', 'todo-los-transport-sse-ws-recovery'],
    dedupeKey: 'los:todo:run-spec-stream-replay',
    metadata: {
      problem: '当前 /chat 是 request-bound SSE，gateway 进程断开后只能从 session_events 手动恢复，不能作为正式 stream replay 合同。',
      solution: '把 run spec 和 stream event read model 分开，idempotency 返回同一 run id。',
      phase: 'ADR0012 Phase 3',
    },
  },
  {
    id: 'todo-los-run-state-tool-state',
    title: '引入 run 状态机和工具调用状态记录',
    description: '为 run 和 tool call 建立 requested/running/succeeded/failed/retrying 等持久状态，使 retry、验证和恢复有明确证据。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'analysis-2026-06-01',
    stageId: 'run-orchestration',
    parentId: 'todo-los-service-cluster-roadmap',
    dependsOnIds: ['todo-los-run-spec-stream-replay'],
    dedupeKey: 'los:todo:run-state-tool-state',
    metadata: {
      problem: '当前工具调用主要是 session event，缺少可恢复的 tool runtime state。',
      solution: '先把状态记录做成审计表，再让 scheduler 使用这些状态做 retry 和 verification。',
      phase: 'ADR0012 Phase 4',
    },
  },
  {
    id: 'todo-los-dag-scheduler',
    title: '在 run spec 和状态机稳定后引入 DAG scheduler',
    description: '新增 agent_tasks、task_edges、task_attempts，按依赖、优先级、成本、置信度和验证状态调度可并行任务。',
    kind: 'task',
    status: 'done',
    priority: 'P2',
    source: 'analysis-2026-06-01',
    stageId: 'run-orchestration',
    parentId: 'todo-los-service-cluster-roadmap',
    dependsOnIds: ['todo-los-run-state-tool-state'],
    dedupeKey: 'los:todo:dag-scheduler',
    metadata: {
      problem: '当前执行是单个 scheduled agent run，无法表达真实任务依赖和并行验证。',
      solution: '已增加最小 agent task graph store、dependency claim query 和 task attempt 证据；完整 runtime graph engine 后续单独推进。',
      phase: 'ADR0012 Phase 5',
      evidence: [
        'contracts/agent-task-graph.yaml',
        'packages/agent/src/agent-task-graph.ts',
        'packages/agent/src/agent-task-graph-read-model.ts',
        'packages/agent/src/agent-task-graph.test.ts',
        'packages/gateway/src/agent-task-graph-routes.ts',
        'packages/gateway/src/agent-task-graph-routes.test.ts',
      ],
      validation: ['agent task graph tests', 'gateway graph route tests', 'agent and gateway check/test', 'contract check'],
    },
  },
  {
    id: 'todo-los-memory-compression-eval',
    title: '分层记忆压缩与质量 eval',
    description: '区分 working/episodic/semantic/procedural memory，记录 success、latency、retry、tool error、verification 和用户反馈等 eval 指标。',
    kind: 'batch',
    status: 'backlog',
    priority: 'P2',
    source: 'analysis-2026-06-01',
    stageId: 'memory-eval',
    parentId: 'todo-los-service-cluster-roadmap',
    dependsOnIds: ['todo-los-dag-scheduler'],
    dedupeKey: 'los:todo:memory-compression-eval',
    metadata: {
      problem: '当前 memory 和 compatibility probes 还不能证明长期质量提升，也不能把重复经验压缩成可审查规则。',
      solution: '增加记忆层标签、压缩任务、证据引用和 eval 指标表。',
      phase: 'ADR0012 Phase 6-7',
    },
  },
  {
    id: 'todo-los-test-db-isolation',
    title: '隔离测试数据库，避免测试任务污染 live todo/task 视图',
    description: 'task-runs 测试当前会写入有效配置的 PostgreSQL，应改为测试 schema、临时 database 或显式 cleanup。',
    kind: 'problem',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'quality',
    dedupeKey: 'los:todo:test-db-isolation',
    dependsOnIds: ['todo-los-saas-foundation'],
    metadata: {
      problem: 'live /tasks 中可见 task-runs.test.ts 写入的 session-1 测试记录。',
      solution: '在 @los/infra initDb 加测试进程 guard：测试默认拒绝写入 live-looking DB，优先使用 TEST_DATABASE_URL，并保留 LOS_ALLOW_LIVE_TEST_DB=1 作为显式一次性 override。',
      evidence: [
        'packages/infra/src/db.ts',
        'packages/infra/src/db.test.ts',
      ],
      validation: [
        'pnpm --filter @los/infra check',
        'node --import tsx --test src/db.test.ts',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  ...LOS_AGENT_WORKFLOW_TODO_SEED,
  ...LOS_RUNTIME_CORE_TODO_SEED,
  ...LOS_GOVERNANCE_TODO_SEED,
];
