import type { CreateTodoInput } from './todo-types.js';

const RESEARCH_SOURCE = 'docs/research/2026-07-16-llm-space-observability-and-execution-optimization.md';

export const _EXECUTION_LAB_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-execution-lab',
    title: '建设 los 原生 Execution Lab',
    description: '把持久化执行证据投影为可比较的 run 视图，再以显式来源关系创建受控实验、成对评价和优化建议。',
    kind: 'phase',
    status: 'backlog',
    priority: 'P0',
    source: 'research-2026-07-16-llm-space',
    stageId: 'execution-lab',
    dependsOnIds: ['todo-los-model-event-projection', 'todo-los-golden-trace-fixtures'],
    dedupeKey: 'los:todo:execution-lab',
    metadata: {
      problem: 'los 已有 session、run、tool、provider 和 verification 证据，但缺少从一次执行创建受控候选并比较结果的统一工作流。',
      decision: '保留 los 的 PostgreSQL 事实模型和统一状态机，只吸收 LLM Space 的 trace-to-workbench、配置 diff 和 pairwise rubric 交互。',
      nonGoals: [
        '不引入 Pi/Electrobun 运行时',
        '不复制 LLM Space 的文件存储模型',
        '不让外部 trace 成为 succeeded 或 verification 证据',
      ],
      research: RESEARCH_SOURCE,
      sequence: [
        'execution-observability-projection',
        'execution-experiment-contract',
        'execution-pairwise-rubric-eval',
        'execution-optimization-analysis',
        'external-trace-adapters',
      ],
    },
  },
  {
    id: 'todo-los-execution-observability-projection',
    title: '投影 execution fingerprint、turn waterfall 与 failure facets',
    description: '从 run_specs、session_events、tool_call_states、provider telemetry 和 verification records 生成可追溯、可重算的执行观测视图。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'research-2026-07-16-llm-space',
    stageId: 'execution-lab',
    parentId: 'todo-los-execution-lab',
    dependsOnIds: [
      'todo-los-execution-lab',
      'todo-los-model-event-projection',
      'todo-los-golden-trace-fixtures',
      'todo-los-tool-call-state-loop-wiring',
    ],
    dedupeKey: 'los:todo:execution-observability-projection',
    metadata: {
      problem: '当前证据分散在多个读模型和页面，无法稳定回答一次执行使用了什么配置、时间花在哪里、失败由哪些持久化事实共同构成。',
      solution: '新增只读 projection；fingerprint 只哈希已持久化版本，缺失输入显式标记 unknown；failure facets 保留多原因及来源引用。',
      priorityReason: 'P0：它不增加执行语义，却是后续实验可比性、故障定位和指标可信度的前置条件。',
      candidateSurfaces: [
        'packages/agent/src/session-trace.ts',
        'packages/agent/src/run-evals.ts',
        'packages/gateway/src/routes/',
        'packages/web/src/pages/session-inspector.tsx',
      ],
      acceptance: [
        'fingerprint 对缺失的 prompt/spec/memory/tool catalog 版本返回 unknown，不从自由文本补值',
        'turn waterfall 的模型等待、工具等待、重试、错误、denied 和 token 汇总可回溯到证据 ID',
        'failure facets 支持 provider、tool、policy、verification、context 和 recovery 多值原因',
        'golden fixtures 覆盖成功、provider error、tool denied、verification failed 和 recovery',
        'projection 不写执行状态，也不创建 verification 记录',
      ],
      research: RESEARCH_SOURCE,
    },
  },
  {
    id: 'todo-los-execution-experiment-contract',
    title: '定义 execution experiment 与单候选 fork/rerun 合同',
    description: '先定义 source evidence、candidate config diff、派生 run_spec 和生命周期合同，再实现显式创建与执行候选的服务。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'research-2026-07-16-llm-space',
    stageId: 'execution-lab',
    parentId: 'todo-los-execution-lab',
    dependsOnIds: [
      'todo-los-execution-observability-projection',
      'todo-los-run-spec-contract-reconciliation',
      'todo-los-verifier-completion-runtime-gate',
    ],
    dedupeKey: 'los:todo:execution-experiment-contract',
    metadata: {
      problem: '现有 branch/resume/retry 能恢复执行，但没有统一表达“从不可变源证据修改一个变量并形成候选 run”的公开合同。',
      solution: 'contract first 定义 experiment provenance、evidence hash、config diff、candidate runSpecId 和 draft/approved/running/terminal 生命周期。',
      priorityReason: 'P1：这是新的跨包与持久化语义，必须建立在可信投影上，并经过 ADR、contract、迁移和 focused harness 审查。',
      requiredDesign: [
        '新增 ADR，明确 fork、rerun、resume 和 retry 的差异',
        '先定义 contracts/execution-experiment.yaml，再改生成类型、store、gateway 和 web',
        'candidate 审批继续通过 approveRunSpecPhase() 或 reviseRunSpecPlan() 持久化 RunContract',
        '任何状态变化继续通过 transitionExecutionState()，成功仍需 canMarkSucceeded()',
        '首次启用实验执行模式需要 operator consent',
      ],
      acceptance: [
        'experiment 只引用源 session/run/event cursor 与 evidence hash，不复制或改写源事件',
        '候选配置差异可枚举且未变字段继承规则明确',
        '创建 draft 不会自动排队或执行，执行必须经过显式审批和工具策略',
        '失败、取消、blocked 和 succeeded 都可回到 experiment provenance',
        'focused harness 固定 provenance、幂等、权限、预算、AP2 和 AP3 行为',
      ],
      research: RESEARCH_SOURCE,
    },
  },
  {
    id: 'todo-los-execution-pairwise-rubric-eval',
    title: '扩展 run_evals 支持 run-pair 与不可变 rubric revision',
    description: '在现有 run_evals 上记录 baseline/candidate、rubric snapshot、criterion score 和 pairwise verdict，并分离人工、judge 与确定性验证。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'research-2026-07-16-llm-space',
    stageId: 'execution-lab',
    parentId: 'todo-los-execution-lab',
    dependsOnIds: ['todo-los-execution-experiment-contract', 'todo-los-execution-observability-projection'],
    dedupeKey: 'los:todo:execution-pairwise-rubric-eval',
    metadata: {
      problem: '当前 run_evals 支持单次记录和时间窗比较，但缺少同源 baseline/candidate 的稳定配对与 rubric 版本语义。',
      solution: '扩展现有 eval 模型，不新建平行评价系统；分别保存 human、judge、deterministic verification 的来源和结果。',
      priorityReason: 'P1：没有成对评价就不能证明候选优于基线，但它依赖 experiment provenance，不能早于实验合同。',
      acceptance: [
        'pair 同时引用 experiment、baseline runSpecId 和 candidate runSpecId',
        'rubric revision 与 criterion 定义按评价时版本不可变快照保存',
        '人工、judge 和 deterministic verification 不合并成无标签总分',
        '成本、延迟、重试和工具错误来自 execution projection，可回溯到源证据',
        'UI 可并排检查配置 diff、waterfall、failure facets、verification 与 rubric',
      ],
      research: RESEARCH_SOURCE,
    },
  },
  {
    id: 'todo-los-execution-optimization-analysis',
    title: '基于配对证据生成执行优化分析',
    description: '按 provider/profile、工具、上下文策略和关键路径聚合实验结果，生成带样本量与证据引用的优化建议。',
    kind: 'task',
    status: 'backlog',
    priority: 'P2',
    source: 'research-2026-07-16-llm-space',
    stageId: 'execution-lab',
    parentId: 'todo-los-execution-lab',
    dependsOnIds: ['todo-los-execution-pairwise-rubric-eval', 'todo-los-provider-compat-harness'],
    dedupeKey: 'los:todo:execution-optimization-analysis',
    metadata: {
      problem: '单次 trace 能解释发生了什么，但不能证明 provider、tool policy 或 context 策略变化在多次任务上稳定改善结果。',
      solution: '聚合同源实验，计算成功率、verification pass rate、成本、延迟、重试、工具输出效率与 critical path 差异。',
      priorityReason: 'P2：分析只有在 P1 产生足够的配对样本后才可靠；过早自动调参会把相关性误当因果。',
      acceptance: [
        '每项建议包含样本范围、配置差异、效果量、失败回归和源 run-pair',
        'provider/profile 比较必须通过 compatibility probe，并区分 configured 与 effective runtime route',
        '工具分析区分成功率、延迟、retry、denied、空结果和输出 token 效率',
        'critical path 基于事件时间与依赖关系，不把并行时长简单相加',
        '建议保持 advisory，不直接修改默认 profile、tool policy 或 context strategy',
      ],
      research: RESEARCH_SOURCE,
    },
  },
  {
    id: 'todo-los-external-trace-adapters',
    title: '增加 Langfuse/OTel/本地 agent trace 导入适配器',
    description: '把外部 trace 映射为带 provenance 和完整性报告的 experiment draft 输入，不进入 los 运行时事实或 verification。',
    kind: 'task',
    status: 'backlog',
    priority: 'P3',
    source: 'research-2026-07-16-llm-space',
    stageId: 'execution-lab',
    parentId: 'todo-los-execution-lab',
    dependsOnIds: ['todo-los-execution-experiment-contract', 'todo-los-execution-observability-projection'],
    dedupeKey: 'los:todo:external-trace-adapters',
    metadata: {
      problem: 'Langfuse、OTel 与本地 agent 日志可扩充比较样本，但字段、截断、权限和完整性不能满足 los 原生执行证据要求。',
      solution: '建立 adapter boundary，保留 source、cursor、import time、mapping version、redaction 和 dropped-field report。',
      priorityReason: 'P3：外部覆盖面不是当前主缺口；先完成 los 原生实验链路，才能定义稳定且不会污染事实所有权的映射。',
      acceptance: [
        '导入只创建 experiment draft 和 external provenance，不创建 task success 或 verification',
        '未知事件保留原始类型与 mapping warning，不静默丢弃',
        '记录分页/数量上限、截断、缺失字段、时区和时间精度',
        '敏感 prompt、tool input/output 经过显式 redaction 与 operator review',
        'adapter fixtures 覆盖 Langfuse、OTel 和至少一种本地 agent 日志',
      ],
      research: RESEARCH_SOURCE,
    },
  },
];
