import type { CreateTodoInput } from './todo-types.js';

/**
 * Context Engineering todo seeds — split from todo-seeds-agent-workflow.ts
 * to stay under the 600-line CI limit.
 *
 * These entries were produced by the 2026-06-20 competitive research sweep.
 * They define the context window management pipeline:
 *   fill monitoring → semantic eviction → compaction hooks → deferred loading → dual-path eval
 */
export const CONTEXT_ENGINEERING_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-context-engineering-phase',
    title: '补齐上下文窗口管理的三层策略 (fill monitor → semantic eviction → optimized compaction)',
    description: 'los 已有 fill monitor、deterministic compression 和 semantic eviction 初版；当前按 Grok Build 对照结果修正 context fill 真值、逐出证据接线，再推进 compaction 生命周期。',
    kind: 'phase',
    status: 'in_progress',
    priority: 'P0',
    source: 'research-sweep-2026-06-20 + grok-build-deep-dive-2026-07-16',
    stageId: 'context-engineering',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-workflow-harness'],
    dedupeKey: 'los:todo:context-engineering-phase',
    metadata: {
      problem: '初版功能已存在，但 provider usage 的累计语义和 persisted tool-result 接线尚未被 focused fixture 证明。',
      solution: '按 fill truth → persisted eviction → compaction lifecycle 顺序修正，每步先完成 focused regression test。',
      researchInputs: [
        'docs/research/competitive-snapshot-2026-06-20.md',
        'arXiv:2606.11213 CWL: Structured Context Eviction',
        'Zylos Research: AI Agent Context Window Management 2026',
      ],
    },
  },
  {
    id: 'todo-los-context-fill-monitoring',
    title: '实现上下文填充率三级监控 (60% warn / 75% checkpoint / 85% compact)',
    description: '修正 loop.ts 的 context fill 计量：当前上下文使用量以最新一次 provider request usage 为准，不跨轮重复累计历史 prompt；保留累计 usage 仅用于成本与会话统计。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'research-sweep-2026-06-20 + grok-build-deep-dive-2026-07-16',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:context-fill-monitoring',
    metadata: {
      problem: 'monitor 跨轮累加 promptTokens；provider prompt usage 通常已包含本轮完整历史，导致旧上下文被重复计算并可能过早触发 critical。',
      solution: 'fill 使用最新 prompt + 当前 completion；累计 prompt/completion 继续作为 usage telemetry，不参与 context window 阈值判断。',
      reference: 'Anthropic effective context engineering, Zylos Research production telemetry',
      thresholds: { warn: 0.60, checkpoint: 0.75, critical: 0.85 },
      candidateFiles: ['packages/agent/src/context-monitor.ts', 'packages/agent/src/context-monitor.test.ts'],
      acceptance: [
        '多轮 prompt usage 不重复累计到 usedTokens',
        '60/75/85% 阈值以当前 context usage 触发',
        'provider 未返回 usage 时保留显式低置信度 fallback',
      ],
      evidence: [
        'packages/agent/src/context-monitor.ts separates cumulative usage from currentContextTokens',
        'packages/agent/src/context-monitor.test.ts covers multi-turn non-accumulation, thresholds, totalTokens, and fallback',
      ],
      validation: [
        'context-monitor.test.ts: 15/15 passed',
        'pnpm --filter @los/agent check',
        'pnpm --filter @los/agent test: 682 passed, 1 skipped, 0 failed',
      ],
      statusUpdatedAt: '2026-07-16',
    },
  },
  {
    id: 'todo-los-semantic-eviction-layer1',
    title: '实现语义逐出 Layer 1 — compaction 前用 masking 替换已持久化的 tool result',
    description: '在 LLM compaction 之前增加无 LLM 参与的 masking 层：对效果已持久化的 tool call（write_edit / read_file / cancelled），用占位符替换原始内容。保留 user turns 和未完成 tool call 的完整内容。参考 CWL 论文的 deterministic eviction。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'research-sweep-2026-06-20 + grok-build-deep-dive-2026-07-16',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-context-fill-monitoring', 'todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:semantic-eviction-layer1',
    metadata: {
      problem: 'semantic eviction 已实现，但 loop 依赖 tool message 的 name/observation_id；tool-runner 当前未携带这些字段，critical 路径可能无法命中。',
      solution: '让 tool result 携带工具名和可验证 persisted location，并用 loop-level fixture 证明 large read result 被替换为可检索 stub。',
      reference: 'arXiv:2606.11213 CWL, JetBrains Research observation masking: 52% cost reduction, +2.6% solve rate',
      candidateFiles: ['packages/agent/src/loop/tool-runner.ts', 'packages/agent/src/semantic-eviction.ts', 'packages/agent/src/semantic-eviction.test.ts'],
      implementationNote: '只有具有 workspace retrieval evidence 的 read/list/tree 结果可 mask；其他结果保持原文。',
      acceptance: [
        'tool messages retain tool name and a retrievable workspace location',
        'large persisted read/list/tree results become bounded stubs at critical fill',
        'unpersisted or ineligible tool results remain unchanged',
      ],
      evidence: [
        'tool-runner returns workspace_path evidence for successful read_file/list_directory/directory_tree calls',
        'loop retains evidence by callId and applies eviction both on critical crossing and after critical tool execution',
        'semantic eviction refuses results without retrieval evidence',
      ],
      validation: [
        'context/eviction/tool-runner/loop focused tests: 59/59 passed',
        'pnpm --filter @los/agent check',
        'pnpm --filter @los/agent test: 682 passed, 1 skipped, 0 failed',
      ],
      statusUpdatedAt: '2026-07-16',
    },
  },
  {
    id: 'todo-los-pre-action-gate',
    title: '实现 pre-action gate — tool call 执行前检查已知失败模式',
    description: '统一内置 loop 与 operator tool-gate 的失败指纹/fragile-file 来源：两条路径使用同一 canonical fingerprint 和 session_events 持久证据投影，重启或切换 gateway 后可恢复。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'research-sweep-2026-06-20 + runtime-audit-2026-07-16',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:pre-action-gate',
    metadata: {
      problem: 'preActionGate 已接入 tool-runner 和 operator route，但 gateway 使用进程内 Set，loop 通过 any 读取未声明字段，两条路径不会共享或恢复失败证据。',
      solution: '定义 serializable AgentConfig.preActionGate；loop 与 operator route 统一读写 session_events 中的 canonical failure/fragile-file evidence，project 查询保持 tenant 隔离。',
      reference: 'arXiv:2606.12329 projectmem, Claude Code PreToolUse hooks',
      candidateFiles: [
        'packages/agent/src/pre-action-gate.ts',
        'packages/agent/src/pre-action-evidence.ts',
        'packages/agent/src/loop/setup.ts',
        'packages/agent/src/loop/tool-runner.ts',
        'packages/gateway/src/routes/orchestration/tool-gate-routes.ts',
      ],
      nonGoals: ['不自动 block tool call（除非 operator 显式配置）', '不替代 operator attestation (ADR 0020)'],
      evidence: [
        'AgentConfig.preActionGate is typed and inherited by child-agent execution config',
        'pre-action-evidence.ts projects canonical failure fingerprints and fragile files from session_events',
        'tool-runner records tool.pre_action.failure and warns matching later calls in the same loop',
        'operator routes restore feedback across Fastify instances and persist fragile-file add/remove events',
      ],
      validation: [
        'pre-action/evidence/tool-runner/session-visibility focused tests: 30/30 passed',
        'gateway tool-gate focused tests: 2/2 passed',
        'pnpm --filter @los/agent test: 686 passed, 1 skipped, 0 failed',
        'pnpm --filter @los/gateway test: 105 passed, 0 failed',
        './tools/check-contracts.sh',
        'pnpm gate: 9 phases passed, 0 failed',
      ],
      statusUpdatedAt: '2026-07-16',
    },
  },
  {
    id: 'todo-los-architect-editor-separation',
    title: '实现 Architect/Editor 双模型分离 — reasoning 模型规划 + editing 模型执行',
    description: '参考 Aider architect mode：对复杂代码修改，先用 reasoning-first 模型做规划，输出自然语言方案描述；再用 editing-first 模型（使用简化 editor-diff prompt）转化为具体编辑指令。与 P0-2 Judge Model 共用双 provider 基础设施。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-agent-mode-contracts', 'todo-los-provider-capability-profile', 'todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:architect-editor-separation',
    metadata: {
      problem: '当前用同一个 model 同时推理和编辑。Aider 实验证明分离后 DeepSeek 作为 Editor 意外优秀，专属简化 prompt 可减少 lazy coding 3x。',
      solution: '扩展 run contract mode 增加 architect-editor 选项；loop.ts 区分 planning turn 和 editing turn；editor 使用简化 prompt（只输出 edit 指令）。',
      reference: 'Aider architect mode: aider.chat/docs/usage/modes.html, aider.chat/2024/09/26/architect.html',
      candidateFiles: ['packages/agent/src/loop.ts', 'packages/agent/src/run-contract.ts', 'packages/agent/src/model-profiles.ts'],
      nonGoals: ['不强制所有 task', '不替代 P0-2 Judge Model'],
    },
  },
  {
    id: 'todo-los-compaction-hooks',
    title: '实现 PreCompact/PostCompact 生命周期钩子',
    description: '在 compaction pipeline 中增加钩子点：PreCompact — 写 checkpoint + 保存 context 快照 + 通知 operator；PostCompact — 重建引用文件 + 重新加载工具定义 + 记录 compaction 效果指标。参考 Claude Code hooks 系统。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-semantic-eviction-layer1', 'todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:compaction-hooks',
    metadata: {
      problem: 'compaction 当前是黑盒操作，无 pre/post 通知、无 checkpoint 保护、无效果回测。丢失关键信息无法恢复。',
      solution: '在 compactSession() 中增加 hook 点；PreCompact 写 session checkpoint + 通知；PostCompact 重建 context（re-read 最近 5 个引用文件 + re-declare tool definitions）。',
      reference: 'Claude Code PreCompact/PostCompact hooks, v2.1.128 compaction beta',
      candidateFiles: ['packages/memory/src/compaction.ts', 'packages/gateway/src/chat-service.ts'],
      hookEvents: ['pre_compact', 'post_compact'],
    },
  },
  {
    id: 'todo-los-deferred-tool-loading',
    title: '实现 Deferred Tool Loading — 启动时只加载 tool name，按需获取完整 schema',
    description: '当前 registry.ts 全量加载所有 tool schema 到 system prompt。如果 tool 数量增长（50+ MCP tools），context overhead 线性增长。参考 Claude Code ToolSearch：启动时只加载 name + 1-line description，首次调用时获取完整 schema。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:deferred-tool-loading',
    metadata: {
      problem: '全量加载 tool schema 当前 ~10 tools 无问题，但 MCP 扩展后可能 50+ tools。Claude Code 实验证明 deferred loading 降低 context overhead 一个数量级。',
      solution: '两级注册：name + 1-line description (always loaded) vs full JSON schema (on-demand via lazy load + cache)。',
      reference: 'Claude Code 2026 Deferred Tool Loading, alexop.dev full-stack guide',
      candidateFiles: ['packages/agent/src/registry.ts', 'packages/agent/src/loop.ts'],
      nonGoals: ['不改变 tool 注册 API 外部接口', '不延迟 tool execution path (schema cache <1ms)'],
    },
  },
  {
    id: 'todo-los-dual-path-compaction',
    title: '评估双路径 compaction — 本地透明 compaction + 可选服务端 compaction',
    description: '当 Anthropic compact endpoint 可用时，做 A/B 对比：本地 transparent compaction vs 服务端 compaction 在摘要注意力保持、token 节省、恢复质量上的差异。参考 Codex CLI 的双路径设计。决策后决定是否引入服务端路径。',
    kind: 'plan',
    status: 'backlog',
    priority: 'P2',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-semantic-eviction-layer1', 'todo-los-compaction-hooks', 'todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:dual-path-compaction',
    metadata: {
      problem: '纯 LLM summarization 有信息丢失风险；服务端 compaction 可能质量更高但不透明。',
      solution: '先完成本地 3-layer pipeline，稳定后 A/B 对比。保留本地 transparent compaction 为默认。',
      reference: 'Codex CLI POST /v1/responses/compact architecture',
      candidateFiles: ['packages/memory/src/compaction.ts'],
      nonGoals: ['不替代本地 transparent compaction', '不把 compaction 决策权交给外部服务'],
    },
  },
];
