import type { CreateTodoInput } from './todo-types.js';

/**
 * Context Engineering todo seeds — split from todo-seeds-agent-workflow.ts
 * to stay under the 600-line CI limit.
 *
 * These entries were produced by the 2026-06-20 competitive research sweep.
 * They define the context window management pipeline:
 *   fill monitoring → semantic eviction → compaction hooks → deferred loading → dual-path eval
 */
export const CONTEXT_ENGINEERING_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-context-engineering-phase',
    title: '补齐上下文窗口管理的三层策略 (fill monitor → semantic eviction → optimized compaction)',
    description: 'los 当前在上下文窗口管理上是完全空白的——无填充率监控、无分层逐出、无 compaction 钩子。本轮调研发现 CWL 论文的 masking 策略可在不增加 LLM 调用成本的情况下降低 52% 上下文消耗且提升 2.6% 解决率。',
    kind: 'phase',
    status: 'backlog',
    priority: 'P0',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-workflow-harness'],
    dedupeKey: 'los:todo:context-engineering-phase',
    metadata: {
      problem: '所有头部竞品都有成熟的上下文管理方案，los 唯一完全空白。有效上下文只有窗口 70-80%。',
      solution: 'Phase 分包：先监控 → 再逐出 → 再优化。每步有独立测量指标。',
      researchInputs: [
        'docs/research/competitive-snapshot-2026-06-20.md',
        'arXiv:2606.11213 CWL: Structured Context Eviction',
        'Zylos Research: AI Agent Context Window Management 2026',
      ],
    },
  },
  {
    id: 'todo-los-context-fill-monitoring',
    title: '实现上下文填充率三级监控 (60% warn / 75% checkpoint / 85% compact)',
    description: '在 loop.ts 每个 model turn 后追踪 token usage，计算 context fill%，按阈值触发：60% log warn + 切换到 targeted file read；75% 写 checkpoint；85% 触发 compaction。利用 Messages API usage 字段。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:context-fill-monitoring',
    metadata: {
      problem: '对 context window 使用量完全无感知。200K 窗口实际可用 ~140-160K，超过 60% 开始劣化。',
      solution: '利用 API response usage 字段计算 fill%。loop.ts 每个 model turn 后检查，chat-service 注入 threshold callbacks。',
      reference: 'Anthropic effective context engineering, Zylos Research production telemetry',
      thresholds: { warn: 0.60, checkpoint: 0.75, critical: 0.85 },
      candidateFiles: ['packages/agent/src/loop.ts', 'packages/gateway/src/chat-service.ts'],
    },
  },
  {
    id: 'todo-los-semantic-eviction-layer1',
    title: '实现语义逐出 Layer 1 — compaction 前用 masking 替换已持久化的 tool result',
    description: '在 LLM compaction 之前增加无 LLM 参与的 masking 层：对效果已持久化的 tool call（write_edit / read_file / cancelled），用占位符替换原始内容。保留 user turns 和未完成 tool call 的完整内容。参考 CWL 论文的 deterministic eviction。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-context-fill-monitoring', 'todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:semantic-eviction-layer1',
    metadata: {
      problem: '当前 compaction 直接全量 LLM summarization，每次触发摧毁缓存前缀 + 阻塞 LLM + 可能丢失细节。',
      solution: '利用 session_events event type + tool_call_state 判断哪些 content 可安全 mask：write_edit→persisted→mask；read_file→consumed→mask；cancelled→drop；user message→keep。',
      reference: 'arXiv:2606.11213 CWL, JetBrains Research observation masking: 52% cost reduction, +2.6% solve rate',
      candidateFiles: ['packages/memory/src/compaction.ts', 'packages/agent/src/session-events.ts'],
      implementationNote: 'masked content kept in raw log for audit; only active context gets placeholders',
    },
  },
  {
    id: 'todo-los-pre-action-gate',
    title: '实现 pre-action gate — tool call 执行前检查已知失败模式',
    description: '在 tool call 执行前检查当前操作是否匹配已知失败模式：重复失败的操作、编辑已知脆弱的文件。参考 projectmem 的 Memory-as-Governance 理念和 Claude Code PreToolUse hooks。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:pre-action-gate',
    metadata: {
      problem: '没有 pre-execution guard——agent 可能重复已知失败的操作。已有 procedural rules 是被动检索的，不是主动拦截的。',
      solution: '在 tool gate 中增加 pre-action 检查：查找同一/跨 session 的相同 tool + 相似 params 的失败记录。匹配时 warn（非 block），写入 gate_result。',
      reference: 'arXiv:2606.12329 projectmem, Claude Code PreToolUse hooks',
      candidateFiles: ['packages/agent/src/tool-call-gate.ts', 'packages/agent/src/tool-call-states.ts', 'packages/memory/src/retrieval.ts'],
      nonGoals: ['不自动 block tool call（除非 operator 显式配置）', '不替代 operator attestation (ADR 0020)'],
    },
  },
  {
    id: 'todo-los-architect-editor-separation',
    title: '实现 Architect/Editor 双模型分离 — reasoning 模型规划 + editing 模型执行',
    description: '参考 Aider architect mode：对复杂代码修改，先用 reasoning-first 模型做规划，输出自然语言方案描述；再用 editing-first 模型（使用简化 editor-diff prompt）转化为具体编辑指令。与 P0-2 Judge Model 共用双 provider 基础设施。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-agent-mode-contracts', 'todo-los-provider-capability-profile', 'todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:architect-editor-separation',
    metadata: {
      problem: '当前用同一个 model 同时推理和编辑。Aider 实验证明分离后 DeepSeek 作为 Editor 意外优秀，专属简化 prompt 可减少 lazy coding 3x。',
      solution: '扩展 run contract mode 增加 architect-editor 选项；loop.ts 区分 planning turn 和 editing turn；editor 使用简化 prompt（只输出 edit 指令）。',
      reference: 'Aider architect mode: aider.chat/docs/usage/modes.html, aider.chat/2024/09/26/architect.html',
      candidateFiles: ['packages/agent/src/loop.ts', 'packages/agent/src/run-contract.ts', 'packages/agent/src/model-profiles.ts'],
      nonGoals: ['不强制所有 task', '不替代 P0-2 Judge Model'],
    },
  },
  {
    id: 'todo-los-compaction-hooks',
    title: '实现 PreCompact/PostCompact 生命周期钩子',
    description: '在 compaction pipeline 中增加钩子点：PreCompact — 写 checkpoint + 保存 context 快照 + 通知 operator；PostCompact — 重建引用文件 + 重新加载工具定义 + 记录 compaction 效果指标。参考 Claude Code hooks 系统。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-semantic-eviction-layer1', 'todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:compaction-hooks',
    metadata: {
      problem: 'compaction 当前是黑盒操作，无 pre/post 通知、无 checkpoint 保护、无效果回测。丢失关键信息无法恢复。',
      solution: '在 compactSession() 中增加 hook 点；PreCompact 写 session checkpoint + 通知；PostCompact 重建 context（re-read 最近 5 个引用文件 + re-declare tool definitions）。',
      reference: 'Claude Code PreCompact/PostCompact hooks, v2.1.128 compaction beta',
      candidateFiles: ['packages/memory/src/compaction.ts', 'packages/gateway/src/chat-service.ts'],
      hookEvents: ['pre_compact', 'post_compact'],
    },
  },
  {
    id: 'todo-los-deferred-tool-loading',
    title: '实现 Deferred Tool Loading — 启动时只加载 tool name，按需获取完整 schema',
    description: '当前 registry.ts 全量加载所有 tool schema 到 system prompt。如果 tool 数量增长（50+ MCP tools），context overhead 线性增长。参考 Claude Code ToolSearch：启动时只加载 name + 1-line description，首次调用时获取完整 schema。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:deferred-tool-loading',
    metadata: {
      problem: '全量加载 tool schema 当前 ~10 tools 无问题，但 MCP 扩展后可能 50+ tools。Claude Code 实验证明 deferred loading 降低 context overhead 一个数量级。',
      solution: '两级注册：name + 1-line description (always loaded) vs full JSON schema (on-demand via lazy load + cache)。',
      reference: 'Claude Code 2026 Deferred Tool Loading, alexop.dev full-stack guide',
      candidateFiles: ['packages/agent/src/registry.ts', 'packages/agent/src/loop.ts'],
      nonGoals: ['不改变 tool 注册 API 外部接口', '不延迟 tool execution path (schema cache <1ms)'],
    },
  },
  {
    id: 'todo-los-dual-path-compaction',
    title: '评估双路径 compaction — 本地透明 compaction + 可选服务端 compaction',
    description: '当 Anthropic compact endpoint 可用时，做 A/B 对比：本地 transparent compaction vs 服务端 compaction 在摘要注意力保持、token 节省、恢复质量上的差异。参考 Codex CLI 的双路径设计。决策后决定是否引入服务端路径。',
    kind: 'plan',
    status: 'backlog',
    priority: 'P2',
    source: 'research-sweep-2026-06-20',
    stageId: 'context-engineering',
    parentId: 'todo-los-context-engineering-phase',
    dependsOnIds: ['todo-los-semantic-eviction-layer1', 'todo-los-compaction-hooks', 'todo-los-context-engineering-phase'],
    dedupeKey: 'los:todo:dual-path-compaction',
    metadata: {
      problem: '纯 LLM summarization 有信息丢失风险；服务端 compaction 可能质量更高但不透明。',
      solution: '先完成本地 3-layer pipeline，稳定后 A/B 对比。保留本地 transparent compaction 为默认。',
      reference: 'Codex CLI POST /v1/responses/compact architecture',
      candidateFiles: ['packages/memory/src/compaction.ts'],
      nonGoals: ['不替代本地 transparent compaction', '不把 compaction 决策权交给外部服务'],
    },
  },
];
