/** Review remediation tasks from the 2026-07-28 two-day change audit. */
import type { CreateTodoInput } from './todo-types.js';

const reviewMetadata = {
  reviewDate: '2026-07-28',
  reviewRange: '499fc6b3e66603cba4d24b250119f969460ad7ee..01d1dfd18ac4c6577e392497d580b57cc11ddd6c',
};

export const REVIEW_2026_07_28_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-review-20260728-remediation',
    title: '修复 2026-07-28 两日变更审查发现',
    description: '修复 ACP、session recovery、compaction context、provider routing 和交付状态中的已确认缺陷。',
    kind: 'plan',
    status: 'in_progress',
    priority: 'P0',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    dedupeKey: 'los:review:20260728:remediation',
    metadata: {
      ...reviewMetadata,
      findingCount: 8,
      validation: ['focused regression tests', 'pnpm check', 'pnpm run gate'],
    },
  },
  {
    id: 'todo-los-review-20260728-recovery-summary',
    title: '对齐 compaction checkpoint 与 session recovery schema',
    description: '持久化并读取 tool state、文件引用和消息游标，避免最新 compaction 恢复为空状态。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    parentId: 'todo-los-review-20260728-remediation',
    dedupeKey: 'los:review:20260728:recovery-summary',
    metadata: {
      ...reviewMetadata,
      relatedTodoIds: ['todo-los-gap-cr-protocol', 'todo-los-gap-cr-tool-state'],
      files: [
        'contracts/session-recovery.yaml',
        'packages/memory/src/core/compaction.ts',
        'packages/gateway/src/chat-service-hooks.ts',
        'packages/agent/src/session-recovery.ts',
      ],
      acceptance: [
        'compaction summary persists the recovery checkpoint fields defined by the contract',
        'recovery reads a real checkpoint without empty fallback state',
      ],
      validation: ['@los/memory compaction-recovery.test.ts', '@los/agent check', '@los/gateway check'],
    },
  },
  {
    id: 'todo-los-review-20260728-checkpoint-selection',
    title: '修复 recovery checkpoint 选择语义',
    description: '默认选择最新 checkpoint，并实现 targetCheckpointId 的精确选择和无效目标错误。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    parentId: 'todo-los-review-20260728-remediation',
    dedupeKey: 'los:review:20260728:checkpoint-selection',
    metadata: {
      ...reviewMetadata,
      relatedTodoIds: ['todo-los-gap-cr-reconstruct'],
      files: ['contracts/session-recovery.yaml', 'packages/agent/src/session-recovery.ts'],
      acceptance: ['multiple checkpoints select the newest by default', 'targetCheckpointId is honored exactly'],
      validation: ['@los/agent session-recovery-checkpoints.test.ts'],
    },
  },
  {
    id: 'todo-los-review-20260728-tool-state-events',
    title: '修复 compaction tool state 事件标识',
    description: '从 execution transition payload 读取工具调用实体 id，并保证 pending/result 状态可正确迁移。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    parentId: 'todo-los-review-20260728-remediation',
    dependsOnIds: ['todo-los-review-20260728-recovery-summary'],
    dedupeKey: 'los:review:20260728:tool-state-events',
    metadata: {
      ...reviewMetadata,
      relatedTodoIds: ['todo-los-gap-cr-tool-state'],
      files: ['packages/gateway/src/chat-service-hooks.ts', 'packages/agent/src/execution-store.ts'],
      validation: ['@los/gateway chat-service-hooks.test.ts'],
    },
  },
  {
    id: 'todo-los-review-20260728-postcompact-context',
    title: '移除未注入 agent 的 PostCompact 伪 context',
    description: '删除只发送 operator SSE、却没有进入本地或远端 agent 消息历史的伪 context 重建。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    parentId: 'todo-los-review-20260728-remediation',
    dependsOnIds: ['todo-los-review-20260728-tool-state-events'],
    dedupeKey: 'los:review:20260728:postcompact-context',
    metadata: {
      ...reviewMetadata,
      relatedTodoIds: ['todo-los-gap-ch-postcompact-refiles'],
      files: ['packages/gateway/src/chat-service-hooks.ts'],
      resolution: 'Removed SSE-only file-context and tool-catalog claims; loop/executor-owned injection remains in the related design Todo.',
      validation: ['@los/gateway check', 'pnpm check:wiring'],
    },
  },
  {
    id: 'todo-los-review-20260728-recovery-tests',
    title: '替换 session recovery 占位测试',
    description: '用真实 fixture 覆盖 compaction round-trip、多 checkpoint、目标 checkpoint、工具状态和文件陈旧检测。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    parentId: 'todo-los-review-20260728-remediation',
    dependsOnIds: [
      'todo-los-review-20260728-recovery-summary',
      'todo-los-review-20260728-checkpoint-selection',
      'todo-los-review-20260728-tool-state-events',
    ],
    dedupeKey: 'los:review:20260728:recovery-tests',
    metadata: {
      ...reviewMetadata,
      relatedTodoIds: ['todo-los-gap-cr-fixture'],
      files: ['packages/agent/src/session-recovery.test.ts'],
      validation: [
        '@los/agent session-recovery.test.ts',
        '@los/agent session-recovery-checkpoints.test.ts',
        '@los/agent stream-checkpoints-latest.test.ts',
      ],
    },
  },
  {
    id: 'todo-los-review-20260728-acp-dispatch',
    title: '让 ACP 对未实现执行能力 fail-closed',
    description: '在完整 dispatch/streaming/approval 路径可用前，不得宣称支持或接受后吞掉 prompt。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    parentId: 'todo-los-review-20260728-remediation',
    dedupeKey: 'los:review:20260728:acp-dispatch',
    metadata: {
      ...reviewMetadata,
      files: ['packages/gateway/src/routes/acp.ts', 'packages/gateway/src/server.ts'],
      acceptance: ['advertised capabilities match runtime behavior', 'prompt requests cannot succeed without dispatch'],
      resolution: 'Removed the rejected ACP gateway route; ADR 0031 keeps los-mcp as the sole programmatic adapter.',
      validation: ['@los/gateway programmatic-interface-boundary.test.ts', 'pnpm check:contracts'],
    },
  },
  {
    id: 'todo-los-review-20260728-provider-routing',
    title: '接线或降级 provider health routing 声明',
    description: '将 health/affinity 选择接入生产 scheduler，并补 harness；否则删除运行时能力声明。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    parentId: 'todo-los-review-20260728-remediation',
    dedupeKey: 'los:review:20260728:provider-routing',
    metadata: {
      ...reviewMetadata,
      files: [
        'packages/agent/src/providers/provider-health.ts',
        'packages/agent/src/providers/route-healthy.ts',
        'tools/wiring-topology-baseline.txt',
      ],
      acceptance: ['no zero-caller routing capability remains', 'production fallback path retains focused regression coverage'],
      resolution: 'Removed the zero-caller health/affinity router; production remains on compatibility-gated providerFallback.',
      validation: ['@los/agent provider-routing-boundary.test.ts', 'pnpm check:wiring'],
    },
  },
  {
    id: 'todo-los-review-20260728-forgejo-sync',
    title: '完成 GitHub 到 Forgejo 权威 main 的受保护同步',
    description: '修复项验证通过后，通过 Forgejo PR 将 sync/github-main-to-forgejo 合入 origin/main。',
    kind: 'task',
    status: 'blocked',
    priority: 'P0',
    source: 'review-2026-07-28',
    stageId: 'review-remediation',
    parentId: 'todo-los-review-20260728-remediation',
    dependsOnIds: [
      'todo-los-review-20260728-recovery-tests',
      'todo-los-review-20260728-acp-dispatch',
      'todo-los-review-20260728-provider-routing',
    ],
    dedupeKey: 'los:review:20260728:forgejo-sync',
    metadata: {
      ...reviewMetadata,
      blocker: 'code remediation, green exact-head checks, and explicit delivery authorization',
      originMainAtReview: 'e13a06bc2af820c998008da1833a37cc54194bd5',
      syncBranchAtReview: '01d1dfd18ac4c6577e392497d580b57cc11ddd6c',
    },
  },
];
