import type { CreateTodoInput } from './todo-types.js';

export const LOS_RUNTIME_CORE_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-runtime-core-hardening-2026-06-13',
    title: '按 Pi/Hermes 对比收敛 los runtime core hardening',
    description: '把小核心可插拔、运行时安全守卫、可解释调度和证据投影收敛成 los 自己的底层执行优化批次。',
    kind: 'phase',
    status: 'in_progress',
    priority: 'P0',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-runtime-evidence-kg'],
    dedupeKey: 'los:todo:runtime-core-hardening-2026-06-13',
    metadata: {
      analysisInputs: [
        'https://deepakness.com/blog/pi-agent-setup/',
        '/Users/echerlos/syncthing/project/hermes-agent',
        '/Users/echerlos/syncthing/project/pi',
      ],
      sequence: [
        'child-run-contract-propagation',
        'scheduler-decision-ledger',
        'golden-trace-fixtures',
        'steering-session-branching',
        'provider-capability-profile',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-child-run-contract-propagation',
    title: '把父 run contract 传播到 child agent 和 executor node',
    description: '让 spawn_agent child 和 executor HTTP 执行路径继承当前 runContractMetadata，避免子执行绕开 phase/tool/verification 约束。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-verifier-completion-runtime-gate'],
    dedupeKey: 'los:todo:child-run-contract-propagation',
    metadata: {
      problem: 'child agent 和 executor node 如果只继承 provider/model/toolMode，就可能绕开父 run contract 的 phase 和验证边界。',
      solution: '在 spawn_agent runner 与 scheduled executor request 中传递当前 runContractMetadata，并用 focused tests 固定。',
      evidence: [
        'packages/agent/src/tools/agent-tools.ts',
        'packages/agent/src/loop.ts',
        'packages/agent/src/scheduler/scheduled-task-runner.ts',
        'packages/agent/src/tools/registry.test.ts',
        'packages/agent/src/scheduler.test.ts',
      ],
      validation: [
        'pnpm --filter @los/agent test -- --test-name-pattern "spawn_agent child inherits parent run contract metadata"',
        'pnpm --filter @los/agent test -- --test-name-pattern "scheduler phase gate reads current run spec contract"',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-scheduler-decision-ledger',
    title: '持久化 scheduler decision ledger',
    description: '记录候选任务、候选节点、选择理由、跳过理由、能力缺口、editable-surface 冲突和成本/延迟估计。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-child-run-contract-propagation'],
    dedupeKey: 'los:todo:scheduler-decision-ledger',
    metadata: {
      problem: '当前 task claim 和 executor selection 可运行，但调度理由没有可复盘的持久化证据。',
      solution: '新增 scheduler_decisions ledger，记录 graph claim 与 provider selection 的 why selected / why skipped，并接入 graph scheduler tests。',
      evidence: [
        'packages/agent/src/scheduler-decision-ledger.ts',
        'packages/agent/src/scheduler/claim-decision.ts',
        'packages/agent/src/agent-task-graph.ts',
        'packages/agent/src/scheduler.ts',
        'packages/agent/src/scheduler/executor-client.ts',
        'packages/agent/src/scheduler/scheduled-task-runner.ts',
        'packages/agent/src/scheduler.test.ts',
      ],
      validation: [
        'pnpm --filter @los/agent test -- --test-name-pattern "scheduler runs independent graph tasks in parallel|scheduler selects graph task provider"',
        'pnpm --filter @los/agent check',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-golden-trace-fixtures',
    title: '为执行事件投影增加 golden trace fixtures',
    description: '把 raw session_events、projection/read-model 和 UI view-model 分层固定，新增事件类型时必须同步 fixture。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-scheduler-decision-ledger'],
    dedupeKey: 'los:todo:golden-trace-fixtures',
    metadata: {
      problem: 'UI 如果直接消费 raw ledger，新增事件类型会把复杂度推到视图层。',
      solution: '建立 raw session_events -> projectSessionTrace -> gateway trace messages 的 golden fixture gate，防止 trace UI 漂移。',
      evidence: [
        'packages/agent/src/session-trace-fixtures.ts',
        'packages/agent/src/session-trace.test.ts',
        'packages/gateway/src/trace-routes.test.ts',
      ],
      validation: [
        'node --import tsx --import ./src/test-setup.ts --test --test-concurrency 1 src/session-trace.test.ts',
        'pnpm --filter @los/gateway test -- --test-name-pattern "session trace route matches golden"',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-steering-session-branching',
    title: '设计 operator steering 与 session branch 控制面',
    description: '把 Pi 风格 steering/follow-up/session tree 映射为 los 的 operator event、turn-boundary drain 和 branch lineage。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-golden-trace-fixtures'],
    dedupeKey: 'los:todo:steering-session-branching',
    metadata: {
      problem: '长会话中途纠偏和分支实验目前主要依赖聊天上下文，而不是 durable control events。',
      solution: '新增 operator.steering/operator.followup/session.branch_created durable events；gateway 暴露 POST /sessions/:id/operator-events，/chat branch 写入 session.branch_created lineage。',
      evidence: [
        'packages/agent/src/operator-control.ts',
        'packages/gateway/src/routes/session-routes.ts',
        'packages/gateway/src/chat-service.ts',
        'contracts/run-stream.yaml',
      ],
      validation: [
        'pnpm --filter @los/agent check',
        'pnpm --filter @los/gateway check',
        'node --import tsx --import ./src/test-setup.ts --test --test-concurrency 1 src/operator-control.test.ts',
        'pnpm --filter @los/gateway test -- --test-name-pattern "operator-events"',
        './tools/check-contracts.sh',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-provider-capability-profile',
    title: '把 provider/model 兼容下沉为 capability profile',
    description: '用能力画像表达 reasoning、vision、tool streaming、cache/session affinity、model alias 和 proxy 组合，供调度器选择。',
    kind: 'task',
    status: 'ready',
    priority: 'P1',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-child-run-contract-propagation'],
    dedupeKey: 'los:todo:provider-capability-profile',
    metadata: {
      problem: 'DeepSeek/Anthropic-compatible 等 provider 不能只按 provider 名称或 API 协议判断兼容性。',
      solution: '把 modelName alias、reasoning 支持、vision proxy、tool streaming 和 cache/session affinity 记录为 capability profile。',
      statusUpdatedAt: '2026-06-13',
    },
  },
];
