import type { CreateTodoInput } from './todo-types.js';

export const LOS_AGENT_WORKFLOW_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-agent-workflow-harness',
    title: '把个人高自治 agent 工作流固化为 los 证据 harness',
    description: '以审计/执行/收尾三档模式、完成定义、工具链矩阵和 eval 样本集定义 los 的短期治理目标。',
    kind: 'phase',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-governance-module-boundary',
    dependsOnIds: ['todo-los-governance-module-boundary'],
    dedupeKey: 'los:todo:agent-workflow-harness',
    metadata: {
      problem: '现有路线已经覆盖 provider、service cluster、run state 和周期治理，但还没有把高自治 agent 使用方式前置成可验证任务契约。',
      solution: '先用治理文档和 todo 元数据表达三档模式、验证契约、工具链矩阵和失败样本 eval，再决定是否进入 CLI/UI 字段或 runtime schema。',
      doc: 'docs/governance/agent-workflow-roadmap.md',
    },
  },
  {
    id: 'todo-los-agent-mode-contracts',
    title: '定义审计/执行/收尾三档启动契约',
    description: '把任务启动时的模式、可编辑范围、必跑检查、允许跳过项、停下来询问条件和提交边界写成可复用模板。',
    kind: 'task',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-workflow-harness'],
    dedupeKey: 'los:todo:agent-mode-contracts',
    metadata: {
      problem: '长任务如果只靠自然语言“继续”推进，容易扩大范围或事后补验证。',
      solution: '先在文档和 todo metadata 中固定 mode contract；稳定后再考虑 CLI/UI 字段。',
      modes: ['audit', 'execution', 'closeout'],
    },
  },
  {
    id: 'todo-los-toolchain-matrix',
    title: '建立 agent toolchain matrix',
    description: '记录 Codex、Claude、OpenCode、Reasonix、OMX、Gemini 和浏览器工具的用途、模型/路由、权限、记忆位置、证据质量和禁用条件。',
    kind: 'task',
    status: 'backlog',
    priority: 'P1',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-mode-contracts'],
    dedupeKey: 'los:todo:toolchain-matrix',
    metadata: {
      problem: '多工具并行使用时，配置真相、运行时真相、记忆位置、权限模式和证据质量容易漂移。',
      solution: '先做 redacted governance matrix；任何导入外部日志的动作都必须另走 ADR 和 redaction contract。',
      candidateDoc: 'docs/governance/toolchain-matrix.md',
    },
  },
  {
    id: 'todo-los-personal-eval-corpus',
    title: '建立个人 agent 失败样本 eval 集',
    description: '从历史失败模式提炼 20-50 个窄 eval，覆盖 dirty worktree、runtime truth、provider gate、jj、外部 transcript、legacy 边界和验证缺失。',
    kind: 'batch',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-mode-contracts'],
    dedupeKey: 'los:todo:personal-eval-corpus',
    metadata: {
      problem: '只增加 prompt 或规则不能持续提高 agent 可靠性；需要把失败模式转成可复查样本。',
      solution: '每个 eval 记录 trigger、bad answer pattern、required evidence、passing pattern 和 owner surface，再决定进入测试、harness、smoke 或 doc checklist。',
      initialFamilies: [
        'dirty-worktree-formatter',
        'runtime-vs-config-truth',
        'provider-readiness-vs-compatibility',
        'jj-status',
        'external-transcript-boundary',
        'legacy-reference-boundary',
      ],
    },
  },
];
