import type { CreateTodoInput } from './todo-types.js';

export const LOS_AGENT_WORKFLOW_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-agent-workflow-harness',
    title: '把个人高自治 agent 工作流固化为 los 证据 harness',
    description: '以审计/执行/收尾三档模式、完成定义、工具链矩阵和 eval 样本集定义 los 的短期治理目标。',
    kind: 'phase',
    status: 'ready',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-governance-module-boundary',
    dependsOnIds: ['todo-los-governance-module-boundary'],
    dedupeKey: 'los:todo:agent-workflow-harness',
    metadata: {
      problem: '现有路线已经覆盖 provider、service cluster、run state 和周期治理，但还没有把高自治 agent 使用方式前置成可验证任务契约。',
      solution: '先用治理文档和 todo 元数据表达三档模式、验证契约、工具链矩阵和失败样本 eval，再决定是否进入 CLI/UI 字段或 runtime schema。',
      doc: 'docs/governance/agent-workflow-roadmap.md',
      sequence: [
        'governance-artifacts',
        'run-contract-metadata',
        'runtime-state-reconciliation',
        'external-summary-adapter',
        'planner-executor-verifier-dag',
      ],
    },
  },
  {
    id: 'todo-los-agent-execution-gap-plan',
    title: '完成 agent 执行缺口阶段路线设计',
    description: '基于 Codex、Claude Code、Reasonix、OpenCode 和 OMX 的边界对比，明确当前、短期和长期的 agent 执行缺口。',
    kind: 'plan',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-workflow-harness'],
    dedupeKey: 'los:todo:agent-execution-gap-plan',
    metadata: {
      evidence: [
        'docs/governance/agent-execution-gap-plan.md',
        'docs/governance/agent-workflow-roadmap.md',
      ],
      result: '设计记录已进入项目治理文档；后续任务按 todo 依赖推进，不放入全局规则层。',
      ownerLayer: 'project docs and todos',
    },
  },
  {
    id: 'todo-los-agent-mode-contracts',
    title: '定义审计/执行/收尾三档启动契约',
    description: '把任务启动时的模式、可编辑范围、必跑检查、允许跳过项、停下来询问条件和提交边界写成可复用模板。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-execution-gap-plan'],
    dedupeKey: 'los:todo:agent-mode-contracts',
    metadata: {
      problem: '长任务如果只靠自然语言“继续”推进，容易扩大范围或事后补验证。',
      solution: '先在文档和 todo metadata 中固定 mode contract；稳定后再考虑 CLI/UI 字段。',
      evidence: [
        'docs/governance/agent-workflow-roadmap.md',
        'docs/governance/run-contract-template.md',
      ],
      modes: ['audit', 'execution', 'closeout'],
    },
  },
  {
    id: 'todo-los-run-contract-template',
    title: '完成 run contract 文档模板',
    description: '固化 mode、goal、editable surfaces、required checks、stop conditions、evidence 和 commit boundary 的任务契约模板。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-mode-contracts'],
    dedupeKey: 'los:todo:run-contract-template',
    metadata: {
      evidence: ['docs/governance/run-contract-template.md'],
      result: '模板先作为项目治理文档使用；runtime 字段由后续 metadata/schema 任务验证。',
      ownerLayer: 'project governance doc',
    },
  },
  {
    id: 'todo-los-toolchain-matrix',
    title: '建立 agent toolchain matrix',
    description: '记录 Codex、Claude、OpenCode、Reasonix、OMX、Gemini 和浏览器工具的用途、模型/路由、权限、记忆位置、证据质量和禁用条件。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-run-contract-template'],
    dedupeKey: 'los:todo:toolchain-matrix',
    metadata: {
      problem: '多工具并行使用时，配置真相、运行时真相、记忆位置、权限模式和证据质量容易漂移。',
      solution: '先做 redacted governance matrix；任何导入外部日志的动作都必须另走 ADR 和 redaction contract。',
      evidence: ['docs/governance/toolchain-matrix.md'],
      comparedTools: ['Codex', 'Claude Code', 'Reasonix', 'OpenCode', 'OMX', 'Gemini', 'Browser tools'],
    },
  },
  {
    id: 'todo-los-personal-eval-corpus',
    title: '建立个人 agent 失败样本 eval 集',
    description: '从历史失败模式提炼 20-50 个窄 eval，覆盖 dirty worktree、runtime truth、provider gate、jj、外部 transcript、legacy 边界和验证缺失。',
    kind: 'batch',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-toolchain-matrix'],
    dedupeKey: 'los:todo:personal-eval-corpus',
    metadata: {
      problem: '只增加 prompt 或规则不能持续提高 agent 可靠性；需要把失败模式转成可复查样本。',
      solution: '每个 eval 记录 trigger、bad answer pattern、required evidence、passing pattern 和 owner surface，再决定进入测试、harness、smoke 或 doc checklist。',
      evidence: ['docs/governance/eval-backlog.md'],
      initialCaseCount: 20,
      initialFamilies: [
        'dirty-worktree-formatter',
        'runtime-vs-config-truth',
        'provider-readiness-vs-compatibility',
        'jj-status',
        'external-transcript-boundary',
        'legacy-reference-boundary',
      ],
    },
  },
  {
    id: 'todo-los-run-contract-metadata',
    title: '把 run contract 接入 todo/task metadata',
    description: '在不强制改 runtime schema 的前提下，让 todo/task 能记录 mode、required checks、allowed skips、stop conditions、evidence 和 commit boundary。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-personal-eval-corpus'],
    dedupeKey: 'los:todo:run-contract-metadata',
    metadata: {
      problem: '文档模板不能被任务派发和复盘稳定查询。',
      solution: '先用 metadata 记录契约字段并补 focused tests；稳定后再决定 CLI/UI 字段和 run_specs schema extensions。',
      evidence: [
        'packages/agent/src/run-contract.ts',
        'packages/agent/src/todos.ts',
        'packages/agent/src/task-runs.ts',
        'packages/agent/src/scheduler.ts',
        'packages/agent/src/run-contract.test.ts',
        'packages/agent/src/todos.test.ts',
        'packages/agent/src/task-runs.test.ts',
      ],
      candidateFields: [
        'mode',
        'requiredChecks',
        'allowedSkips',
        'stopConditions',
        'evidenceRequired',
        'commitBoundary',
      ],
      validation: ['agent todo tests', 'gateway todo route tests if API shape changes'],
    },
  },
  {
    id: 'todo-los-run-spec-contract-reconciliation',
    title: '校准现有 run_specs 与 run contract 字段',
    description: '现有 /chat 已创建基础 run_specs；需要补齐 mode、goal、验证要求、停问条件和外部证据边界的接入策略。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'run-orchestration',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-run-contract-metadata', 'todo-los-run-spec-stream-replay'],
    dedupeKey: 'los:todo:run-spec-contract-reconciliation',
    metadata: {
      problem: '代码层已有 run_specs 表和 /chat 创建路径，但字段还偏执行参数，缺少 operator contract。',
      currentEvidence: [
        'packages/agent/src/run-specs.ts',
        'packages/gateway/src/chat-route.ts',
        'packages/gateway/src/server.ts',
      ],
      solution: '先补 schema/input 映射和测试，再决定 /runs/:id/events?since= 的 replay 合同。',
      evidence: [
        'packages/agent/src/run-specs.ts',
        'packages/gateway/src/chat-route.ts',
        'packages/agent/src/run-specs.test.ts',
      ],
      validation: ['run spec create/load route test', 'agent and gateway type checks'],
    },
  },
  {
    id: 'todo-los-tool-call-state-loop-wiring',
    title: '把 tool_call_states 接入 agent loop 和 scheduler',
    description: '现有 tool_call_states 表尚未被 loop 写入；需要把 tool requested/running/succeeded/failed/retrying 状态变成可查询运行证据。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'run-orchestration',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-run-spec-contract-reconciliation', 'todo-los-run-state-tool-state'],
    dedupeKey: 'los:todo:tool-call-state-loop-wiring',
    metadata: {
      problem: 'tool_call_states 已有 CRUD，但 rg 显示 create/update 只导出，尚未在 loop 执行路径调用。',
      currentEvidence: [
        'packages/agent/src/tool-call-states.ts',
        'packages/agent/src/loop.ts',
        'packages/agent/src/scheduler.ts',
      ],
      solution: '围绕 tool call 生命周期补写入点、失败/重试状态和 focused tests。',
      evidence: [
        'packages/agent/src/loop.ts',
        'packages/agent/src/scheduler.ts',
        'packages/agent/src/tool-call-states.ts',
        'packages/agent/src/scheduler.test.ts',
      ],
      validation: ['scheduler tool state persistence test', 'agent and gateway type checks'],
    },
  },
  {
    id: 'todo-los-verification-state-records',
    title: '把验证要求和 skipped checks 变成运行状态',
    description: '为 run contract 中的 required checks、allowed skips、执行结果和跳过原因建立可查询记录，避免只靠最终汇报文本。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-run-spec-contract-reconciliation'],
    dedupeKey: 'los:todo:verification-state-records',
    metadata: {
      problem: '当前验证结果主要靠 agent 汇报和操作文档，不能作为 run state 查询。',
      solution: '先随 run contract 记录 verification requirements；再增加 verifier events/tasks。',
      evidence: [
        'packages/agent/src/verification-records.ts',
        'packages/agent/src/run-specs.ts',
        'packages/agent/src/verification-records.test.ts',
        'packages/agent/src/run-specs.test.ts',
      ],
      validation: ['verification records test', 'run spec required-check projection test'],
    },
  },
  {
    id: 'todo-los-provider-promotion-evidence-record',
    title: '持久化 provider promotion 证据',
    description: '把 provider readiness、credential class、compat probe、usage/cost 和 promotion decision 关联到 taskRun/session/runSpec。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-06-05',
    stageId: 'provider-governance',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-run-spec-contract-reconciliation'],
    dedupeKey: 'los:todo:provider-promotion-evidence-record',
    metadata: {
      problem: 'provider readiness 与 verified advisory promotion 还缺少可查询的历史证据记录。',
      solution: '从 compat runs 或 task/session events 投影 provider_compat evidence，再让 provider list 只展示有证据的 verified 状态。',
      adr: 'docs/adr/0017-advisory-provider-promotion-playbook.md',
      evidence: [
        'packages/agent/src/provider-compat-evidence.ts',
        'packages/agent/src/provider-compat-evidence.test.ts',
        'packages/cli/src/compat.ts',
        'packages/gateway/src/server.ts',
      ],
      validation: ['provider compat evidence test', 'agent/cli/gateway type checks'],
    },
  },
  {
    id: 'todo-los-agent-eval-harness-wire',
    title: '把高风险 agent eval 样本接入测试或 harness',
    description: '先把 dirty worktree、runtime/config truth、provider gate、external transcript、jj 和 todo-done 六类样本变成可运行检查。',
    kind: 'batch',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-verification-state-records'],
    dedupeKey: 'los:todo:agent-eval-harness-wire',
    metadata: {
      problem: 'eval backlog 仍是文档，不会自动阻止行为回归。',
      solution: '将最高风险样本逐步投到 tests、harness probes、operation smokes 或 review checklist。',
      evidence: [
        'docs/governance/eval-backlog.md',
        'packages/agent/src/eval-backlog.test.ts',
      ],
      firstCases: ['E01', 'E02', 'E03', 'E04', 'E05', 'E06'],
      validation: ['agent eval backlog test', 'agent test'],
    },
  },
  {
    id: 'todo-los-external-tool-summary-adapter',
    title: '设计 redacted external tool summary adapter',
    description: '为 Codex、Claude Code、Reasonix、OpenCode 和 OMX 的摘要输入定义 schema、provenance、redaction fixture 和禁止原始日志入库规则。',
    kind: 'task',
    status: 'done',
    priority: 'P2',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-agent-eval-harness-wire', 'todo-los-provider-promotion-evidence-record'],
    dedupeKey: 'los:todo:external-tool-summary-adapter',
    metadata: {
      problem: '外部工具对比目前只能人工阅读，且原始 transcript/auth/log 不能直接成为 los 证据。',
      solution: '先定义只接受摘要的 adapter 和 redaction tests；任何 runtime ingestion 另走 ADR。',
      evidence: [
        'docs/governance/toolchain-matrix.md',
        'docs/governance/external-tool-summary-adapter.md',
        'packages/agent/src/external-tool-summary.ts',
        'packages/agent/src/external-tool-summary.test.ts',
      ],
      blockedByPolicy: ['docs/adr/0015-external-transcript-truncation-and-run-replay-policy.md', 'docs/adr/0016-omx-tool-level-logging-scope.md'],
      validation: ['external tool summary adapter test', 'agent test'],
    },
  },
  {
    id: 'todo-los-planner-executor-verifier-dag',
    title: '在状态可观测后设计 planner/executor/verifier DAG',
    description: '等 run spec、tool state、verification state 和 eval 指标可查询后，再把 planner、executor、verifier 作为最小 DAG 节点引入。',
    kind: 'task',
    status: 'backlog',
    priority: 'P2',
    source: 'analysis-2026-06-05',
    stageId: 'agent-workflow-harness',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-external-tool-summary-adapter', 'todo-los-dag-scheduler'],
    dedupeKey: 'los:todo:planner-executor-verifier-dag',
    metadata: {
      problem: '多 agent 协作如果早于 run/tool/verification state，会变成不可恢复的 peer chat。',
      solution: '复用 ADR0012 DAG scheduler 方向，但让 verifier task 可以阻塞完成状态。',
      validation: ['parallel independent tasks smoke', 'failed dependency blocks downstream', 'verifier failure blocks completion'],
    },
  },
];
