import type { CreateTodoInput } from './todo-types.js';

export const _DAILY_AGENT_PRODUCT_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-daily-agent-product',
    title: '把 LOS 建成 Web-first 日常 coding/project Agent',
    description: '优先完成可持久化、可验证、可恢复的 Work-first 日常编码路径，替代 Pi/Codex 核心工作流；Hermes 渠道和消费工具广度独立推进。',
    kind: 'phase',
    status: 'in_progress',
    priority: 'P0',
    source: 'decision-2026-07-21',
    stageId: 'daily-agent-product',
    dedupeKey: 'los:todo:daily-agent-product',
    metadata: {
      decision: 'Web-first persistent verifiable daily coding/project agent first; Hermes breadth is a separate product track.',
      adr: 'docs/adr/0038-web-first-daily-coding-agent-product-boundary.md',
      externalTrigger: 'https://cursor.com/blog/agent-swarm-model-economics',
      sequence: [
        'planning-disposition',
        'web-work-first-intake',
        'approval-execution-resume',
        'verification-revision-loop',
        'scenario-economics',
        'small-governed-graphs',
      ],
      nonGoals: [
        'unrestricted swarm concurrency',
        'automatic merge or release',
        'Hermes channel and consumer-tool parity in P0',
      ],
    },
  },
  {
    id: 'todo-los-daily-agent-direction-record',
    title: '固定 daily Agent 产品边界和交付顺序',
    description: '用 ADR 区分 Pi/Codex 核心替代、后续小规模 task graph 和独立的 Hermes 广度路线。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'decision-2026-07-21',
    stageId: 'daily-agent-product',
    parentId: 'todo-los-daily-agent-product',
    dependsOnIds: [],
    dedupeKey: 'los:todo:daily-agent-direction-record',
    metadata: {
      evidence: [
        'docs/adr/0038-web-first-daily-coding-agent-product-boundary.md',
        'docs/governance/2026-07-18-los-pi-harness-capability-and-operability-audit.md',
        'docs/governance/2026-07-19-web-first-daily-agent-workflow-design.md',
      ],
      statusUpdatedAt: '2026-07-21',
    },
  },
  {
    id: 'todo-los-daily-agent-planning-disposition',
    title: '让 planning 成为独立的持久化调度阶段',
    description: 'Work Item 启动后用只读 planning attempt 生成并持久化结构化 PlanStep 和 verification mapping，等待审批，不以 lightweight 绕过 AP2。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'decision-2026-07-21',
    stageId: 'daily-agent-product',
    parentId: 'todo-los-daily-agent-product',
    dependsOnIds: ['todo-los-daily-agent-direction-record'],
    dedupeKey: 'los:todo:daily-agent-planning-disposition',
    metadata: {
      problem: 'Work Item draft enters Chat with phase=created, while the scheduler blocks standard execution before the existing planning phase can run; planning text is not persisted as PlanStep[].',
      solution: 'Define a planning-only scheduler disposition, structured planner output contract, transactional plan persistence, approval_required projection, and focused AP2 regression tests.',
      startedAt: '2026-07-21',
      implementationEvidence: [
        'packages/agent/src/scheduler/planning-disposition.ts',
        'packages/agent/src/run-spec-plans.ts',
        'packages/gateway/src/chat-planning-disposition.ts',
        'packages/agent/src/scheduler-planning.test.ts',
      ],
      evidence: [
        'contracts/run-spec.yaml@0.3.0',
        'contracts/run-stream.yaml@0.4.0',
        'contracts/work-item.yaml@0.4.0',
        'packages/agent/src/planning-output.test.ts',
        'packages/agent/src/run-spec-plans.test.ts',
        'packages/agent/src/scheduler-planning.test.ts',
        'packages/gateway/src/chat-planning-disposition.test.ts',
        'packages/gateway/src/chat-service-outcomes.test.ts',
        'pnpm run gate: 9 phases passed, 0 failures (2026-07-21)',
      ],
      editableSurfaces: [
        'contracts/run-spec.yaml',
        'contracts/work-item.yaml',
        'packages/agent/src/run-contract.ts',
        'packages/agent/src/run-specs.ts',
        'packages/agent/src/scheduler/',
        'packages/gateway/src/chat-service.ts',
      ],
      validation: [
        'planning attempt cannot call code-writing tools',
        'planning output is persisted as valid PlanStep[]',
        'planning completion does not mark run or Work Item succeeded',
        'pnpm --filter @los/agent test',
        'pnpm --filter @los/gateway test',
        './tools/check-contracts.sh',
      ],
      statusUpdatedAt: '2026-07-21',
    },
  },
  {
    id: 'todo-los-daily-agent-web-work-first-intake',
    title: '把 Web 新 coding 目标默认接入 Work Item',
    description: '普通项目写入目标先形成 goal、scope、non-goals、checks 和 stop conditions 草案，再进入 planning，而不是直接创建无合同写执行。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'decision-2026-07-21',
    stageId: 'daily-agent-product',
    parentId: 'todo-los-daily-agent-product',
    dependsOnIds: ['todo-los-daily-agent-planning-disposition'],
    dedupeKey: 'los:todo:daily-agent-web-work-first-intake',
    metadata: {
      problem: 'Ordinary Web Chat may omit runContract, so write-enabled daily use bypasses the Work Item intake and completion contract.',
      solution: 'Make Work-first the default Web coding entry while keeping direct Chat for conversation and bounded lightweight work.',
      validation: [
        'new project-write goal creates or binds one Work Item before planning',
        'direct lightweight Chat remains available',
        'desktop and mobile Web smoke',
      ],
      implementationEvidence: [
        'packages/web/src/hooks/useChatRun.ts',
        'packages/web/src/ui-boundary.test.mjs',
        'packages/web/e2e/work-first-intake.spec.ts',
      ],
      evidence: [
        'pnpm --filter @los/web test: 19 passed (2026-07-21)',
        'pnpm --filter @los/web test:e2e --grep "project-write Chat": desktop and mobile Chromium passed (2026-07-21)',
        'pnpm check: passed (2026-07-21)',
      ],
      statusUpdatedAt: '2026-07-21',
    },
  },
  {
    id: 'todo-los-daily-agent-approval-execution-resume',
    title: '审批后从持久合同启动 execution attempt',
    description: '计划审批后由 coordinator 使用已持久化的 run contract 创建 execution attempt，并在 gateway/browser 重启后从数据库证据恢复。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'decision-2026-07-21',
    stageId: 'daily-agent-product',
    parentId: 'todo-los-daily-agent-product',
    dependsOnIds: ['todo-los-daily-agent-planning-disposition'],
    dedupeKey: 'los:todo:daily-agent-approval-execution-resume',
    metadata: {
      problem: 'Approval currently changes the run phase but does not define a complete Work-first dispatch/resume action using the stored request envelope.',
      solution: 'Dispatch the stored request envelope after approval, use a revision-scoped dedupe key, and recover approved or just-started runs with no persisted execution attempt during Gateway startup.',
      validation: [
        'approve dispatch is idempotent',
        'execution reads persisted plan and request parameters',
        'restart recovery does not duplicate an active attempt',
      ],
      implementationEvidence: [
        'packages/gateway/src/run-resume-dispatch.ts',
        'packages/gateway/src/run-resume-recovery.ts',
        'packages/gateway/src/server.ts',
      ],
      evidence: [
        'packages/gateway/src/run-resume-dispatch.test.ts',
        'packages/gateway/src/run-resume-recovery.test.ts',
        'pnpm --filter @los/gateway check: passed (2026-07-21)',
        'pnpm --filter @los/agent test: passed (2026-07-21)',
        'pnpm --filter @los/gateway test: 124 passed (2026-07-21)',
        'pnpm run gate: 9 phases passed, 15 test tasks passed, 0 failures (2026-07-21)',
      ],
      statusUpdatedAt: '2026-07-21',
    },
  },
  {
    id: 'todo-los-daily-agent-verification-revision-loop',
    title: '把验证失败和 revision_requested 变成下一次持久尝试',
    description: 'required verification 失败或用户请求修订时，创建带证据引用的新计划修订或 recovery attempt，而不是只把 Todo 留在 blocked。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'decision-2026-07-21',
    stageId: 'daily-agent-product',
    parentId: 'todo-los-daily-agent-product',
    dependsOnIds: ['todo-los-daily-agent-approval-execution-resume'],
    dedupeKey: 'los:todo:daily-agent-verification-revision-loop',
    metadata: {
      problem: 'Current gates persist blocked evidence, but the general daily path does not automatically create a bounded revise-and-retry attempt.',
      solution: 'Serialize revisions per Work Item, persist revision lineage and stable feedback fingerprints, stop on repeated failed evidence or retry-budget exhaustion, and emit one durable operator-attention event.',
      validation: [
        'failed verification cannot transition to succeeded',
        'revision preserves plan and attempt lineage',
        'retry budget exhaustion creates one operator attention item',
      ],
      implementationEvidence: [
        'packages/agent/src/work-items/revision-loop.ts',
      ],
      evidence: [
        'packages/agent/src/work-items/revision-loop.test.ts',
        'pnpm --filter @los/agent check: passed (2026-07-21)',
        'pnpm --filter @los/agent test: 764 passed, 1 skipped, 0 failed (2026-07-21)',
        'pnpm check: passed (2026-07-21)',
        'pnpm run gate: 9 phases passed, 15 test tasks passed, 0 failures (2026-07-21)',
      ],
      statusUpdatedAt: '2026-07-21',
    },
  },
  {
    id: 'todo-los-daily-agent-scenario-economics',
    title: '用 daily scenario corpus 验证质量和模型经济性',
    description: '按 planner/worker/reviewer 角色记录成功率、耗时、成本、重试、验证失败和人工介入，形成自动模型路由前的证据。',
    kind: 'batch',
    status: 'done',
    priority: 'P1',
    source: 'decision-2026-07-21',
    stageId: 'daily-agent-product',
    parentId: 'todo-los-daily-agent-product',
    dependsOnIds: ['todo-los-daily-agent-verification-revision-loop'],
    dedupeKey: 'los:todo:daily-agent-scenario-economics',
    metadata: {
      problem: 'Provider compatibility and snapshots do not yet prove that LOS beats the current direct-agent baseline on daily tasks.',
      solution: 'Run representative scenarios with fixed acceptance criteria and compare configured baseline against explicit role-based model combinations.',
      validation: [
        'requested and effective model remain separate',
        'cost is reported by role and scenario',
        'automatic routing remains disabled until an accepted policy has evidence',
      ],
      implementationEvidence: [
        'contracts/daily-agent-scenario-economics.yaml',
        'packages/agent/src/scenario-economics.ts',
        'packages/gateway/src/routes/providers/provider-evidence-routes.ts',
      ],
      evidence: [
        'packages/agent/src/scenario-economics.test.ts: 3 passed, 0 failed (2026-07-21)',
        'packages/gateway/src/scenario-economics-routes.test.ts: 1 passed, 0 failed (2026-07-21)',
        './tools/check-contracts.sh: passed (2026-07-21)',
        'pnpm --filter @los/agent check: passed (2026-07-21)',
        'pnpm --filter @los/agent test: 767 passed, 1 skipped, 0 failed (2026-07-21)',
        'pnpm --filter @los/gateway check: passed (2026-07-21)',
        'pnpm --filter @los/gateway test: 125 passed, 0 failed (2026-07-21)',
        'pnpm check: passed (2026-07-21)',
        'pnpm run gate: 9 phases passed, 15 test tasks passed, 0 failures (2026-07-21)',
        'runSpec daily-scenario-live-20260721-v3: 30/30 completed scenario runs, 90 accepted role records, 0 rejected records',
        'baseline deepseek-v4-flash: 15/15 completed; candidate deepseek-v4-pro: 15/15 completed',
        '96/96 provider HTTP calls succeeded including the two pre-batch smoke reruns; automatic routing remained disabled',
      ],
      collectionStatus: 'ready_for_policy_review',
      nextEvidenceGate: 'Any routing change requires a separate accepted policy and operator approval; this evidence does not promote deepseek-v4-pro or enable automatic routing.',
      statusUpdatedAt: '2026-07-21',
    },
  },
  {
    id: 'todo-los-daily-agent-small-governed-graphs',
    title: '为复杂任务接入 2-4 worker 的受控 task graph',
    description: '在单目标路径稳定后增加动态 task graph、editable-surface ownership、独立 verifier 和显式 integration owner。',
    kind: 'task',
    status: 'done',
    priority: 'P2',
    source: 'decision-2026-07-21',
    stageId: 'daily-agent-product',
    parentId: 'todo-los-daily-agent-product',
    dependsOnIds: ['todo-los-daily-agent-scenario-economics', 'todo-los-p1-test-coverage'],
    dedupeKey: 'los:todo:daily-agent-small-governed-graphs',
    metadata: {
      problem: 'Existing graph primitives expose conservative serial execution and no general operator create/watch/integrate path.',
      solution: 'Start with bounded parallelism and non-overlapping file ownership; measure conflict and operator intervention before increasing scale.',
      graphContract: { minWorkers: 2, maxWorkers: 4, editableSurfaceMode: 'strict', verifierRequired: true, integrationOwnerRequired: true },
      acceptance: ['operator can create, watch, cancel, and inspect the graph', 'only non-overlapping executor nodes may run in parallel', 'failed dependencies block downstream nodes', 'integration waits for verifier success and records operator intervention'],
      stopConditions: ['editable-surface conflict', 'lost task or run lease', 'verification failure after retry budget', 'missing integration owner'],
      nonGoals: ['1000-agent scale', 'automatic merge', 'unbounded recursive delegation'],
      readinessEvidence: ['scenario economics dependency is done with automatic routing still disabled', 'repository coverage baseline and focused blind-spot tests are done', 'existing agent task graph contracts, lease fencing, read model, and conservative serial scheduler tests remain the starting point'],
      implementationEvidence: [
        'contracts/agent-task-graph.yaml',
        'packages/agent/src/agent-task-graph/graph-control.ts',
        'packages/gateway/src/routes/orchestration/agent-task-graph-routes.ts',
        'packages/web/src/pages/agent-graph-control.tsx',
      ],
      validation: [
        'agent graph focused tests: 8 passed, 0 failed',
        'gateway graph route focused tests: 2 passed, 0 failed',
        'web boundary tests: 20 passed, 0 failed',
        'pnpm check: passed',
        'pnpm run gate: 9 phases passed, 0 failures',
        'desktop and 390px mobile Tasks UI smoke: no horizontal overflow',
      ],
      residualRisk: 'Graph control events are stored in agent_tasks.metadata_json; integration remains an explicit operator decision and does not merge, push, or release automatically.',
      statusUpdatedAt: '2026-07-22',
    },
  },
  {
    id: 'todo-los-hermes-product-breadth',
    title: '独立评估 Hermes 渠道和消费工具广度',
    description: '在 daily coding path 之外评估 installer、desktop、消息渠道、browser/media、consumer automation 和远程 backend。',
    kind: 'phase',
    status: 'backlog',
    priority: 'P3',
    source: 'decision-2026-07-21',
    stageId: 'hermes-product-breadth',
    dedupeKey: 'los:todo:hermes-product-breadth',
    metadata: {
      boundary: 'This track must not delay or replace the Web-first daily coding P0 path.',
      requiresDecision: [
        'packaging and installation surface',
        'channel priority and live delivery evidence',
        'consumer browser/media ownership',
        'remote backend abstraction',
      ],
    },
  },
];
