import type { CreateTodoInput } from './todo-types.js';

export const LOS_GOVERNANCE_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-governance-archive-policy',
    title: '定义 todo 归档与活跃工作集策略',
    description: 'done / cancelled todo 在完成后自动或手动归档，默认列表仅显示活跃项，避免完成项堆积干扰调度。',
    kind: 'plan',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'todo-governance',
    dedupeKey: 'los:todo:archive-policy',
    metadata: {
      problem: '大量已完成 todo 继续留在主列表里，会让活跃工作集失真。',
      solution: '引入 archived_at/archive_reason，并在默认查询中隐藏归档项。',
    },
  },
  {
    id: 'todo-los-governance-dependency-graph',
    title: '把 todo 拆分关系建成可追踪依赖图',
    description: '为 parentId 之外的跨任务前置条件增加 depends_on 关系表，便于拆分、阻塞和批次调度。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'todo-governance',
    parentId: 'todo-los-governance-archive-policy',
    dependsOnIds: ['todo-los-governance-archive-policy'],
    dedupeKey: 'los:todo:dependency-graph',
    metadata: {
      problem: 'parentId 只能表示树状拆分，不能表达跨分支依赖。',
      solution: '补 todo_dependencies 表和依赖查询视图。',
    },
  },
  {
    id: 'todo-los-governance-drift-sweeper',
    title: '定期核对 todo 与真实实现的漂移',
    description: '对 ready / in_progress / done todo 做证据核验，发现未更新、重复完成和实现漂移后回写状态或归档。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'todo-governance',
    parentId: 'todo-los-governance-archive-policy',
    dependsOnIds: ['todo-los-governance-archive-policy', 'todo-los-governance-dependency-graph'],
    dedupeKey: 'los:todo:drift-sweeper',
    metadata: {
      problem: 'todo 未及时更新时，页面看到的是计划真相，不是执行真相。',
      solution: '以任务事件、session_events、requestId/traceId 做核验和自动标注。',
      evidence: [
        'packages/agent/src/governance-drift-sweeper.ts — detectGovernanceDrift / sweepGovernanceDrift / sweepWithDriftDetection',
      ],
      implementedAt: '2026-06-25',
    },
  },
  {
    id: 'todo-los-governance-saas-todo-bridge',
    title: '补租户/项目级 todo 派发接口',
    description: '按 tenantId/projectId/stageId 选择 ready 的 task/batch todo，生成 task_run 并回写 trace/request/task 关联。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'todo-governance',
    parentId: 'todo-los-governance-archive-policy',
    dependsOnIds: ['todo-los-governance-dependency-graph', 'todo-los-request-id-ledger'],
    dedupeKey: 'los:todo:saas-todo-bridge',
    metadata: {
      problem: '当前 todo 只能人工改状态，还不能成为真正的派发入口。',
      solution: '在 scheduler 前面加一层可审计的派发门。',
      evidence: [
        'packages/gateway/src/routes/data/saas-todo-routes.ts — POST /tenants/:tenantId/projects/:projectId/todos/dispatch (reconcile + create + governance job audit trail)',
        'packages/gateway/src/routes/data/todo-routes.ts — POST /todos/:id/dispatch (per-todo dispatch with status/kind/dep gates + onTaskEvent callback)',
        'packages/agent/src/todo-dispatch.ts — dispatchTodo core function shared by both routes and MessageRouter',
      ],
      implementedAt: '2026-06-26',
    },
  },
  {
    id: 'todo-los-transport-sse-ws-recovery',
    title: '补 SSE/WS 接入、续传和指数退避策略',
    description: '为 SSE/WS 增加 heartbeat、Last-Event-ID/since 续传、指数退避、jitter、最大退避上限和弱网恢复证据。',
    kind: 'task',
    status: 'backlog',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'transport-recovery',
    dependsOnIds: ['todo-los-request-id-ledger', 'todo-los-task-lease-recovery'],
    dedupeKey: 'los:todo:transport-sse-ws-recovery',
    metadata: {
      problem: '当前 /chat 只是单次 SSE 流式响应，缺少断线续传、WS 通道、退避和恢复读模型。',
      solution: '参考 vpsagentweb 的 SSE replay、agent reconnect max delay 和 WebSocket 路由经验，先固化传输策略和可验证事件。',
      placement: 'tracking in todos; implementation in gateway transport and scheduler recovery layers.',
    },
  },
  {
    id: 'todo-los-governance-module-boundary',
    title: '定义周期治理任务的模块边界',
    description: '明确一致性分析、性能优化、数据结构/存储/架构优化、实现漂移、工具层漂移和热点文件治理不放进 task_runs 主模型。',
    kind: 'plan',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-05-30',
    stageId: 'governance-jobs',
    parentId: 'todo-los-governance-archive-policy',
    dependsOnIds: ['todo-los-governance-dependency-graph'],
    dedupeKey: 'los:todo:governance-module-boundary',
    metadata: {
      problem: '如果把治理目录塞进 Tasks，会把"执行尝试"和"治理工作目录"混成一个真相面。',
      solution: 'Todos 记录治理计划和依赖；task_runs 只记录每次执行；后续独立 governance_jobs/sweeps 存周期性运行配置和结果摘要。',
      placement: 'todo-managed planning, task-run execution evidence, governance module for recurring automation when needed.',
      evidence: [
        'docs/governance/governance-module-boundary.md — three-layer model (todos→task_runs→governance_jobs), category taxonomy, implementation status table',
        'Three governance categories in scope: consistency audit, hotspot detection, architecture drift, tool drift, provider compatibility surveillance',
        'Existing drift detection prototypes: governance-reconciliation.ts, governance-status-constraints.ts, governance-runtime-cleanup.ts',
        'Existing infrastructure: execution-static-graph.ts (drift baseline), runtime-evidence-graph.ts (cross-table projection), external-tool-summary.ts (bounded ingestion)',
      ],
      implementedAt: '2026-06-15',
    },
  },
  {
    id: 'todo-los-governance-periodic-sweeper',
    title: '实现周期性治理 sweeper 和租户级调度策略',
    description: '按 tenant/project 周期执行一致性、性能、存储、架构、实现漂移、工具漂移和热点文件检查，写回 todo/task/session 证据。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'governance-jobs',
    parentId: 'todo-los-governance-module-boundary',
    dependsOnIds: ['todo-los-governance-module-boundary', 'todo-los-request-id-ledger'],
    dedupeKey: 'los:todo:governance-periodic-sweeper',
    metadata: {
      problem: '定时任务如果只是 cron 调用，会缺少租户边界、幂等键、执行 lease 和可追溯结果。',
      solution: '定义 governance job policy、周期、lease、dedupeKey、result summary 和 evidence links，再通过 scheduler 执行。',
      cadenceExamples: ['daily consistency audit', 'weekly hotspot audit', 'release-gate drift audit'],
      evidence: [
        'packages/agent/src/governance-wake.ts — claimNextDueJob (FOR UPDATE SKIP LOCKED) + PG LISTEN/NOTIFY + EventBus + 10min fallback setInterval',
        'packages/agent/src/governance-sweeper.ts — runGovernanceSweep cadence-based dispatch + GA loop integration',
        'packages/agent/src/governance-jobs-schema.ts — 12 SEED_JOBS with cadence/circuit-breaker/dedupeKey',
      ],
      implementedAt: '2026-06-21',
    },
  },
  {
    id: 'todo-los-governance-hotspot-and-tool-drift',
    title: '治理热点文件、实现漂移和工具层漂移',
    description: '识别超大/高频变更/跨层耦合文件，核对工具能力声明与真实行为，并把漂移结果写入 todo metadata 和 session_events。',
    kind: 'batch',
    status: 'backlog',
    priority: 'P1',
    source: 'analysis-2026-05-30',
    stageId: 'governance-jobs',
    parentId: 'todo-los-governance-module-boundary',
    dependsOnIds: ['todo-los-governance-periodic-sweeper'],
    dedupeKey: 'los:todo:hotspot-tool-drift',
    metadata: {
      problem: '历史项目里工具声明、实际实现和热点文件会持续漂移，单次 review 很难长期覆盖。',
      solution: '周期性采集 file churn/size/import boundary/tool capability 与实际执行证据，生成治理 todo 或归档证据。',
      categories: ['implementation_drift', 'tool_drift', 'hotspot_files', 'architecture_drift'],
    },
  },
];
