import type { CreateTodoInput } from './todo-types.js';

export const LOS_RUNTIME_CORE_TODO_SEED: CreateTodoInput[] = [
  {
    id: 'todo-los-runtime-core-hardening-2026-06-13',
    title: '按 Pi/Hermes 对比收敛 los runtime core hardening',
    description: '把小核心可插拔、运行时安全守卫、可解释调度和证据投影收敛成 los 自己的底层执行优化批次。',
    kind: 'phase',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-agent-workflow-harness',
    dependsOnIds: ['todo-los-runtime-evidence-kg'],
    dedupeKey: 'los:todo:runtime-core-hardening-2026-06-13',
    metadata: {
      analysisInputs: [
        'https://deepakness.com/blog/pi-agent-setup/',
        '/Users/echerlos/syncthing/project/hermes-agent',
        '/Users/echerlos/syncthing/project/pi',
      ],
      sequence: [
        'child-run-contract-propagation',
        'scheduler-decision-ledger',
        'golden-trace-fixtures',
        'steering-session-branching',
        'provider-capability-profile',
      ],
      completedChangeDescriptions: [
        'feat: propagate run contracts to child executions',
        'feat: persist scheduler decision ledger',
        'test: add golden session trace fixtures',
        'feat: persist operator steering events',
        'feat: add model capability profiles',
      ],
      validation: [
        'pnpm check',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-child-run-contract-propagation',
    title: '把父 run contract 传播到 child agent 和 executor node',
    description: '让 spawn_agent child 和 executor HTTP 执行路径继承当前 runContractMetadata，避免子执行绕开 phase/tool/verification 约束。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-verifier-completion-runtime-gate'],
    dedupeKey: 'los:todo:child-run-contract-propagation',
    metadata: {
      problem: 'child agent 和 executor node 如果只继承 provider/model/toolMode，就可能绕开父 run contract 的 phase 和验证边界。',
      solution: '在 spawn_agent runner 与 scheduled executor request 中传递当前 runContractMetadata，并用 focused tests 固定。',
      evidence: [
        'packages/agent/src/tools/agent-tools.ts',
        'packages/agent/src/loop.ts',
        'packages/agent/src/scheduler/scheduled-task-runner.ts',
        'packages/agent/src/tools/registry.test.ts',
        'packages/agent/src/scheduler.test.ts',
      ],
      validation: [
        'pnpm --filter @los/agent test -- --test-name-pattern "spawn_agent child inherits parent run contract metadata"',
        'pnpm --filter @los/agent test -- --test-name-pattern "scheduler phase gate reads current run spec contract"',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-scheduler-decision-ledger',
    title: '持久化 scheduler decision ledger',
    description: '记录候选任务、候选节点、选择理由、跳过理由、能力缺口、editable-surface 冲突和成本/延迟估计。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-child-run-contract-propagation'],
    dedupeKey: 'los:todo:scheduler-decision-ledger',
    metadata: {
      problem: '当前 task claim 和 executor selection 可运行，但调度理由没有可复盘的持久化证据。',
      solution: '新增 scheduler_decisions ledger，记录 graph claim 与 provider selection 的 why selected / why skipped，并接入 graph scheduler tests。',
      evidence: [
        'packages/agent/src/scheduler-decision-ledger.ts',
        'packages/agent/src/scheduler/claim-decision.ts',
        'packages/agent/src/agent-task-graph.ts',
        'packages/agent/src/scheduler.ts',
        'packages/agent/src/scheduler/executor-client.ts',
        'packages/agent/src/scheduler/scheduled-task-runner.ts',
        'packages/agent/src/scheduler.test.ts',
      ],
      validation: [
        'pnpm --filter @los/agent test -- --test-name-pattern "scheduler runs independent graph tasks in parallel|scheduler selects graph task provider"',
        'pnpm --filter @los/agent check',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-golden-trace-fixtures',
    title: '为执行事件投影增加 golden trace fixtures',
    description: '把 raw session_events、projection/read-model 和 UI view-model 分层固定，新增事件类型时必须同步 fixture。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-scheduler-decision-ledger'],
    dedupeKey: 'los:todo:golden-trace-fixtures',
    metadata: {
      problem: 'UI 如果直接消费 raw ledger，新增事件类型会把复杂度推到视图层。',
      solution: '建立 raw session_events -> projectSessionTrace -> gateway trace messages 的 golden fixture gate，防止 trace UI 漂移。',
      evidence: [
        'packages/agent/src/session-trace-fixtures.ts',
        'packages/agent/src/session-trace.test.ts',
        'packages/gateway/src/trace-routes.test.ts',
      ],
      validation: [
        'node --import tsx --import ./src/test-setup.ts --test --test-concurrency 1 src/session-trace.test.ts',
        'pnpm --filter @los/gateway test -- --test-name-pattern "session trace route matches golden"',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-steering-session-branching',
    title: '设计 operator steering 与 session branch 控制面',
    description: '把 Pi 风格 steering/follow-up/session tree 映射为 los 的 operator event、turn-boundary drain 和 branch lineage。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-golden-trace-fixtures'],
    dedupeKey: 'los:todo:steering-session-branching',
    metadata: {
      problem: '长会话中途纠偏和分支实验目前主要依赖聊天上下文，而不是 durable control events。',
      solution: '新增 operator.steering/operator.followup/session.branch_created durable events；gateway 暴露 POST /sessions/:id/operator-events，/chat branch 写入 session.branch_created lineage。',
      evidence: [
        'packages/agent/src/operator-control.ts',
        'packages/gateway/src/routes/session-routes.ts',
        'packages/gateway/src/chat-service.ts',
        'contracts/run-stream.yaml',
      ],
      validation: [
        'pnpm --filter @los/agent check',
        'pnpm --filter @los/gateway check',
        'node --import tsx --import ./src/test-setup.ts --test --test-concurrency 1 src/operator-control.test.ts',
        'pnpm --filter @los/gateway test -- --test-name-pattern "operator-events"',
        './tools/check-contracts.sh',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-provider-capability-profile',
    title: '把 provider/model 兼容下沉为 capability profile',
    description: '用能力画像表达 reasoning、vision、tool streaming、cache/session affinity、model alias 和 proxy 组合，供调度器选择。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'analysis-2026-06-13',
    stageId: 'agent-runtime-core-hardening',
    parentId: 'todo-los-runtime-core-hardening-2026-06-13',
    dependsOnIds: ['todo-los-child-run-contract-propagation'],
    dedupeKey: 'los:todo:provider-capability-profile',
    metadata: {
      problem: 'DeepSeek/Anthropic-compatible 等 provider 不能只按 provider 名称或 API 协议判断兼容性。',
      solution: '在 model profile 中新增标准化 ModelCapabilityProfile，表达 modelAliases、reasoning、vision、tool streaming、cache/session affinity 与 routing hints，并让 runtime summary/compat harness 读取该结构。',
      evidence: [
        'packages/agent/src/model-profiles.ts',
        'packages/agent/src/model-profiles.test.ts',
        'packages/agent/src/compat-harness.ts',
      ],
      validation: [
        'pnpm --filter @los/agent check',
        'node --import tsx --import ./src/test-setup.ts --test --test-concurrency 1 src/model-profiles.test.ts src/compat-harness.test.ts',
      ],
      statusUpdatedAt: '2026-06-13',
    },
  },
  {
    id: 'todo-los-resource-constrained-node-profile',
    title: '定义 constrained executor 资源画像字段',
    description: '在 ExecutorNodeRecord/HeartbeatInput/capacity 中补充 resourceClass、RAM/swap/disk/PSI 字段，让 Oracle 1GB 类节点在 Nodes UI 显示资源 blocker 而不是只显示 online。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'oracle-incident-2026-06-15',
    stageId: 'mesh-nodes',
    parentId: 'todo-los-node-registry',
    dependsOnIds: ['todo-los-node-registry'],
    dedupeKey: 'los:todo:resource-constrained-node-profile',
    metadata: {
      problem: 'Oracle 1GB executor /health 正常但资源不适合接任务，当前节点模型没有资源等级层。',
      solution: '新增 resourceClass (control/standard_executor/constrained_executor)，在 capacity 中补 RAM/swap/disk/PSI，在 evaluateExecutorNode 中加入资源 warning。',
      adr: 'docs/adr/0010-node-connectivity-capability-taxonomy.md',
      contract: 'contracts/node-registry.yaml',
      implementation: 'packages/agent/src/executor-nodes.ts (ExecutorNodeRecord, ExecutorNodeCapacity, evaluateExecutorNode)',
      oracleNodeKind: 'executor + constrained_executor',
      evidence: [
        'packages/agent/src/executor-nodes.ts — ResourceClass type, resourceClass field on ExecutorNodeRecord/HeartbeatInput, evaluateExecutorNode resource + constrained checks',
        'packages/agent/src/executor-node-utils.ts — normalization helpers for resourceClass, capacity, capabilities',
        'packages/executor/src/resource-metrics.ts — collectResourceMetrics RAM/swap/PSI, resolveResourceCapabilities deploy_safe/heavy_task_safe',
        'packages/executor/src/index.ts — heartbeat transmits resourceClass, capacity, capabilities',
        'packages/web — Nodes list columns + NodeInspector resource display',
      ],
      implementedAt: '2026-06-15',
    },
  },
  {
    id: 'todo-los-constrained-node-scheduler-policy',
    title: '完善 constrained executor 调度候选降级策略',
    description: 'constrained_executor 可在线但不应接构建、长任务、批量文件任务。Scheduler 应读取 heavy_task_safe/deploy_safe 并写入 schedule decision ledger。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'oracle-incident-2026-06-15',
    stageId: 'mesh-nodes',
    parentId: 'todo-los-node-registry',
    dependsOnIds: ['todo-los-resource-constrained-node-profile'],
    dedupeKey: 'los:todo:constrained-node-scheduler-policy',
    metadata: {
      problem: '当前 evaluateExecutorNode() 把 resource_warning 放在 warnings 而不是 blockers——constrained 节点仍然 candidate=true，可能被分到重任务。',
      solution: 'Scheduler 遴选时应检查 capabilities.heavy_task_safe/deploy_safe，将 task kind 与候选节点能力匹配，拒绝不匹配的分配。',
      adr: 'docs/adr/0010-node-connectivity-capability-taxonomy.md',
      implementation: 'packages/agent/src/executor-nodes.ts (evaluateExecutorNode resource checks), packages/agent/src/scheduler/executor-client.ts (task-node capability matching)',
      evidence: [
        'packages/agent/src/scheduler/executor-client.ts — resolveExecutor checks requiresBuild→heavy_task_safe, requiresDeploy→deploy_safe, skips constrained nodes for heavy work',
        'packages/agent/src/scheduler-decision-ledger.ts — recordSchedulerDecision logs skips with capability reasons',
        'packages/agent/src/scheduler/types.ts — ScheduledExecutorConfig now has requiresBuild/requiresDeploy fields',
      ],
      implementedAt: '2026-06-15',
    },
  },
  {
    id: 'todo-los-constrained-node-deploy-preflight',
    title: '完成 constrained executor 部署 preflight 和 artifact-first 发布路径',
    description: 'setup-node.sh 和 deploy-to-remote.sh 需在 preflight 阶段检查 RAM/swap/disk/PSI，constrained 节点必须走 artifact-first（tar sync），禁止远端 pnpm install。',
    kind: 'task',
    status: 'done',
    priority: 'P0',
    source: 'oracle-incident-2026-06-15',
    stageId: 'mesh-nodes',
    parentId: 'todo-los-node-registry',
    dependsOnIds: ['todo-los-resource-constrained-node-profile'],
    dedupeKey: 'los:todo:constrained-node-deploy-preflight',
    metadata: {
      problem: 'Oracle 节点 1GB RAM 无 swap，远端 pnpm install 触发 OOM。部署脚本尚未区分 constrained vs standard 节点。',
      solution: 'deploy-to-remote.sh 已实现 preflight 资源检查和 phased 命令（sync/install/install-service/restart/verify）；setup-node.sh 已增加 --low-resource 模式。尚缺 executor 构建产物路径和 deploy_safe 门禁。',
      adr: 'docs/adr/0011-node-operations-artifact-transfer.md',
      implementation: 'tools/deploy-to-remote.sh (preflight + sync + install --low-resource), tools/setup-node.sh (preflight_resources + --low-resource)',
      remaining: 'artifact-first 路径：本地 build executor dist，tar 打包 dist+node_modules+deploy，sync 时直接解压，跳过远端 pnpm install',
      evidence: [
        'tools/deploy-to-remote.sh — phased deploy: preflight→sync→install→install-service→restart→verify, supports --low-resource',
        'tools/setup-node.sh — preflight_resources checks RAM/swap/disk, auto-enables --low-resource, low-resource install mode',
        'packages/executor/src/resource-metrics.ts — collectResourceMetrics RAM/swap/PSI, resolveResourceCapabilities deploy_safe/heavy_task_safe',
        'deploy/systemd/ — systemd unit for auto-start',
        'packages/executor/src/maintenance.ts — executor upgrade/restart/rollback via helper script',
        'tools/executor.sh — executor lifecycle: start→stop→restart→upgrade→drain→verify→promote',
      ],
      implementedAt: '2026-06-15',
    },
  },
  {
    id: 'todo-los-1panel-boundary-analysis',
    title: '明确 LOS 与 1Panel 的运维边界',
    description: '审计 Oracle 上 1Panel 管理的 Docker/PG/容器用途，明确 LOS 只替代自己的 health、executor 状态、drain/promote/restart、preflight、日志摘要、artifact/evidence，不替代通用服务器面板。',
    kind: 'task',
    status: 'done',
    priority: 'P1',
    source: 'oracle-incident-2026-06-15',
    stageId: 'mesh-nodes',
    parentId: 'todo-los-node-registry',
    dependsOnIds: ['todo-los-resource-constrained-node-profile'],
    dedupeKey: 'los:todo:1panel-boundary-analysis',
    metadata: {
      problem: 'Oracle 恢复时人工停止了 1Panel 管理的容器；如果 LOS 不声明边界，会走入替代通用面板的错误方向。',
      solution: 'ADR 0022 定义了 LOS 自有运维面（health/executor 状态/deploy/preflight/log/artifact）与不替代项（Docker 管理/应用市场/Web 终端/全量服务器面板）。deploy-to-remote.sh 默认不停止非 LOS 容器。',
      adr: 'docs/adr/0022-1panel-boundary-analysis.md',
      nonGoals: ['Docker 管理 UI', '应用市场安装', 'Web 终端', 'PG 服务器管理', '非 LOS 服务监督'],
      evidence: [
        'docs/adr/0022-1panel-boundary-analysis.md — explicit boundary definition',
        'tools/deploy-to-remote.sh — phased deploy that does not touch non-LOS containers',
        'tools/los-firewall.sh — firewall rules for los ports only',
        'packages/agent/src/node-commands.ts — NodeCommandName restricted to los operations (restart/upgrade/rollback/status/logs/drain/promote)',
        'packages/executor/src/node-command-runner.ts — executor maintenance via tools/executor.sh only',
      ],
      implementedAt: '2026-06-15',
    },
  },
];
