#!/usr/bin/env node

import { runPackageTests } from '../../tools/package-test-runner.mjs';

const sharedProcessTestFiles = [
  'src/auth-middleware.test.ts',
  'src/chat-cbm-symbol-cache.test.ts',
  'src/chat-planning-disposition.test.ts',
  'src/chat-service-hooks.test.ts',
  'src/daily-agent-quality-routes.test.ts',
  'src/execution-experiment-k4-routes.test.ts',
  'src/managed-workspace-routes.test.ts',
  'src/node-routes.test.ts',
  'src/openai-compat-route.test.ts',
  'src/operator-command-transport.test.ts',
  'src/operator-gate.test.ts',
  'src/outbox-diagnostics.test.ts',
  'src/pairwise-sample-gate-routes.test.ts',
  'src/project-routes.test.ts',
  'src/project-store.test.ts',
  'src/programmatic-interface-boundary.test.ts',
  'src/routes/providers/provider-crud-routes.test.ts',
  'src/routes/tools/mcp-routes.test.ts',
  'src/routes/tools/skill-routes.test.ts',
  'src/provider-routes.test.ts',
  'src/run-evals-pairwise-routes.test.ts',
  'src/rate-limit.test.ts',
  'src/request-context.test.ts',
  'src/routes/orchestration/grok-runtime-routes.test.ts',
  'src/routes/orchestration/operator-write-routes.test.ts',
  'src/routes/providers/provider-account-routes.test.ts',
  'src/scheduled-work-routes.test.ts',
  'src/service-routes.test.ts',
  'src/settings-routes.test.ts',
  'src/ssh-config-import.test.ts',
  'src/task-dead-letter-routes.test.ts',
  'src/tool-call-upsert.test.ts',
  'src/tool-gate-routes.test.ts',
  'src/work-item-routes.test.ts',
];

const dbBackedTestFiles = [];

const isolatedDatabaseTestFiles = [
  'src/active-session-failover.test.ts',
  'src/agent-task-graph-routes.test.ts',
  'src/artifact-routes.test.ts',
  'src/chat-context-policy.test.ts',
  'src/chat-intake-events.test.ts',
  'src/chat-resume-guard.test.ts',
  'src/chat-resume-plan.test.ts',
  'src/chat-route.test.ts',
  'src/chat-run-completion.test.ts',
  'src/chat-service-hooks-storm.test.ts',
  'src/chat-service-outcomes.test.ts',
  'src/execution-reliability.test.ts',
  'src/execution-experiment-routes.test.ts',
  'src/external-summary-routes.test.ts',
  'src/idempotency-atomic.test.ts',
  'src/integration-routes.test.ts',
  'src/metrics-routes.test.ts',
  'src/node-command-routes.test.ts',
  'src/provider-compat-routes.test.ts',
  'src/routes/auth-routes.test.ts',
  'src/routes/run-routes.test.ts',
  'src/routes/streaming/ws-routes.test.ts',
  'src/run-evals-routes.test.ts',
  'src/run-events-routes.test.ts',
  'src/run-resume-dispatch.test.ts',
  'src/run-resume-recovery.test.ts',
  'src/scenario-economics-routes.test.ts',
  'src/server-maintenance.test.ts',
  'src/session-routes.test.ts',
  'src/trace-routes.test.ts',
];

runPackageTests({
  packageId: 'gateway',
  sharedProcessTestFiles,
  dbBackedTestFiles,
  isolatedDatabaseTestFiles,
  testSetupFile: './src/test-setup.ts',
  globalSetupFile: './src/test-global-setup.mjs',
});
