/**
 * @los/memory/markdown — MEMORY.md file synchronization.
 *
 * Inspired by JiuwenSwarm's Markdown-file memory.
 * Writes a human-readable MEMORY.md in the workspace root,
 * auto-updated after each new observation.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { getLogger } from '@los/infra/logger';
import type { Observation } from './store.js';

const log = getLogger('memory');

export function syncMemoryMd(
  workspaceRoot: string,
  observations: Pick<Observation, 'title' | 'summary' | 'kind' | 'tags' | 'createdAt'>[],
  title = 'Project Memory',
): void {
  const lines: string[] = [
    `# ${title}`,
    '',
    `> Auto-generated by los memory system. Last updated: ${new Date().toISOString()}`,
    '',
    '## Recent Observations',
    '',
  ];

  if (observations.length === 0) {
    lines.push('_(No observations yet)_');
  } else {
    for (const obs of observations.slice(0, 50)) {
      const tagStr = obs.tags.length > 0 ? ` \`${obs.tags.join('` `')}\`` : '';
      lines.push(`### ${obs.title}`);
      lines.push('');
      if (obs.summary) lines.push(`${obs.summary}`);
      lines.push('');
      lines.push(`- **Kind**: ${obs.kind} | **Date**: ${obs.createdAt.slice(0, 10)}${tagStr}`);
      lines.push('');
    }
  }

  const path = join(workspaceRoot, 'MEMORY.md');
  writeFileSync(path, lines.join('\n'), 'utf-8');
  log.debug(`Synced MEMORY.md — ${observations.length} observations`);
}

export function readMemoryMd(workspaceRoot: string): string | null {
  const path = join(workspaceRoot, 'MEMORY.md');
  if (!existsSync(path)) return null;
  return readFileSync(path, 'utf-8');
}
